export const STORAGE_VERSION = 'v4';
export const STORAGE_KEY = 'trip-canvas6-' + STORAGE_VERSION;

export const COLOR_PALETTES = {
  locations: ['#2D3A64', '#C84E4E', '#7FAFAE', '#EECAD0', '#9A948C', '#F97316', '#2563EB', '#10B981'],
  friends: ['#F7E6EC', '#FFE4F0', '#EAF7EA', '#E6EFFA', '#E5F4F1', '#FEF3C7', '#FCE7F3', '#E0E7FF'],
};

export const DEFAULT_TRIP_TEMPLATE = {
  tripName: 'Japan Trip — Nov 14–30, 2025',
  range: {
    start: '2025-11-14',
    end: '2025-11-30',
  },
  friends: ['Nana', 'Nicole', 'Ken', 'James', 'Phil'],
  friendColors: {
    Nana: '#F7E6EC',
    Nicole: '#FFE4F0',
    Ken: '#EAF7EA',
    James: '#E6EFFA',
    Phil: '#E5F4F1',
  },
  locations: {
    osaka: { label: 'Osaka/Hirakata', color: '#2D3A64' },
    kyoto: { label: 'Kyoto/Nara/Kōyasan', color: '#C84E4E' },
    kobe: { label: 'Kobe/Arima/Himeji', color: '#7FAFAE' },
    tokyo: { label: 'Tokyo/Chiba', color: '#EECAD0' },
    work: { label: 'Work/Travel', color: '#9A948C' },
  },
  locationOrder: ['osaka', 'kyoto', 'kobe', 'tokyo', 'work'],
  defaultThemes: {
    osaka: 'Osaka base day',
    kyoto: 'Old streets & leaves',
    kobe: 'Onsen & castles',
    tokyo: 'Friends & arcades',
    work: 'Travel / admin',
  },
  mapDefaults: { center: [35.0, 135.5], zoom: 5 },
  placeLookups: {
    dotonbori: { query: 'Dotonbori Osaka', region: 'jp', types: ['tourist_attraction'] },
    umedaSky: { query: 'Umeda Sky Building', region: 'jp', types: ['tourist_attraction'] },
    abenoHarukas: { query: 'Abeno Harukas', region: 'jp', types: ['tourist_attraction'] },
    midosujiIllumination: { query: 'Midosuji Illumination', region: 'jp', types: ['tourist_attraction'] },
    arashiyama: { query: 'Arashiyama Bamboo Grove', region: 'jp', types: ['tourist_attraction'] },
    kiyomizudera: { query: 'Kiyomizu-dera Temple', region: 'jp', types: ['tourist_attraction'] },
    fushimiInari: { query: 'Fushimi Inari Taisha', region: 'jp', types: ['tourist_attraction'] },
    uji: { query: 'Byodoin Temple Uji', region: 'jp', types: ['tourist_attraction'] },
    naraPark: { query: 'Nara Park', region: 'jp', types: ['tourist_attraction'] },
    okunoin: { query: 'Okunoin Temple Koyasan', region: 'jp', types: ['tourist_attraction'] },
    eikando: { query: 'Eikando Zenrinji Temple', region: 'jp', types: ['tourist_attraction'] },
    rurikoin: { query: 'Rurikoin Temple Kyoto', region: 'jp', types: ['tourist_attraction'] },
    arimaOnsen: { query: 'Arima Onsen', region: 'jp', types: ['tourist_attraction'] },
    harborland: { query: 'Kobe Harborland', region: 'jp', types: ['shopping_mall'] },
    himejiCastle: { query: 'Himeji Castle', region: 'jp', types: ['tourist_attraction'] },
    disneyResort: { query: 'Tokyo Disney Resort', region: 'jp', types: ['tourist_attraction'] },
    teamlabPlanets: { query: 'teamLab Planets TOKYO', region: 'jp', types: ['tourist_attraction'] },
    ghibliMuseum: { query: 'Ghibli Museum', region: 'jp', types: ['tourist_attraction'] },
    shibuyaParco: { query: 'Shibuya PARCO', region: 'jp', types: ['shopping_mall'] },
    takeshitaStreet: { query: 'Takeshita Street', region: 'jp', types: ['tourist_attraction'] },
    sunshine60: { query: 'Sunshine City Ikebukuro', region: 'jp', types: ['shopping_mall'] },
    animateIkebukuro: { query: 'Animate Ikebukuro Flagship Store', region: 'jp', types: ['book_store'] },
    akihabara: { query: 'Akihabara Electric Town', region: 'jp', types: ['tourist_attraction'] },
    harajukuVintage: { query: 'Harajuku vintage shops', region: 'jp' },
    roppongiMidtown: { query: 'Tokyo Midtown Roppongi', region: 'jp', types: ['shopping_mall'] },
    dxbAirport: { query: 'Dubai International Airport Terminal 3', region: 'ae', types: ['airport'] },
    kix: { query: 'Kansai International Airport Terminal 1', region: 'jp', types: ['airport'] },
    hirakatashi: { query: 'Hirakatashi Station', region: 'jp', types: ['transit_station'] },
    usj: { query: 'Universal Studios Japan', region: 'jp', types: ['tourist_attraction'] },
    'stay-candeo-hirakata': { query: 'Candeo Hotels Osaka Hirakata', region: 'jp', types: ['lodging'] },
    'stay-sunplaza-hirakata': { query: 'Sun Plaza Hotel Hirakata', region: 'jp', types: ['lodging'] },
    'stay-cross-hotel-osaka': { query: 'Cross Hotel Osaka', region: 'jp', types: ['lodging'] },
    'stay-the-thousand-kyoto': { query: 'The Thousand Kyoto', region: 'jp', types: ['lodging'] },
    'stay-hotel-granvia-kyoto': { query: 'Hotel Granvia Kyoto', region: 'jp', types: ['lodging'] },
    'stay-ekoin-koyasan': { query: 'Ekoin Temple Koyasan', region: 'jp', types: ['lodging'] },
    'stay-arima-grand': { query: 'Arima Grand Hotel', region: 'jp', types: ['lodging'] },
    'stay-la-suite-kobe': { query: 'Hotel La Suite Kobe Harborland', region: 'jp', types: ['lodging'] },
    'stay-mitsui-garden-otemachi': { query: 'Mitsui Garden Hotel Otemachi', region: 'jp', types: ['lodging'] },
    'stay-hotel-niwa-tokyo': { query: 'Hotel Niwa Tokyo', region: 'jp', types: ['lodging'] },
    'stay-airbnb-tokyo': { query: 'Tokyo Station Area', region: 'jp' },
    'stay-disney-ambassador': { query: 'Disney Ambassador Hotel', region: 'jp', types: ['lodging'] },
    'stay-disneyland-hotel': { query: 'Tokyo Disneyland Hotel', region: 'jp', types: ['lodging'] },
    'stay-disney-celebration': { query: 'Tokyo Disney Celebration Hotel', region: 'jp', types: ['lodging'] },
  },
  mapCoordinates: {
    dotonbori: [34.6687, 135.5013],
    umedaSky: [34.7051, 135.4899],
    abenoHarukas: [34.6464, 135.5134],
    midosujiIllumination: [34.6865, 135.4983],
    arashiyama: [35.0136, 135.6736],
    kiyomizudera: [34.9948, 135.785],
    fushimiInari: [34.9671, 135.7727],
    uji: [34.8846, 135.8033],
    naraPark: [34.6851, 135.843],
    okunoin: [34.215, 135.5858],
    eikando: [35.0156, 135.7967],
    rurikoin: [35.0866, 135.7869],
    arimaOnsen: [34.7968, 135.2495],
    harborland: [34.6785, 135.1787],
    himejiCastle: [34.8393, 134.6939],
    disneyResort: [35.6339, 139.8864],
    teamlabPlanets: [35.6496, 139.7916],
    ghibliMuseum: [35.6962, 139.5704],
    shibuyaParco: [35.6605, 139.6983],
    takeshitaStreet: [35.6717, 139.7029],
    sunshine60: [35.7296, 139.7178],
    animateIkebukuro: [35.7317, 139.7153],
    akihabara: [35.6987, 139.7714],
    harajukuVintage: [35.6695, 139.7058],
    roppongiMidtown: [35.6665, 139.7316],
    dxbAirport: [25.2532, 55.3657],
    kix: [34.4338, 135.2263],
    hirakatashi: [34.8165, 135.6477],
    usj: [34.6654, 135.4323],
    'stay-candeo-hirakata': [34.8139, 135.6499],
    'stay-sunplaza-hirakata': [34.8145, 135.6493],
    'stay-cross-hotel-osaka': [34.6689, 135.5022],
    'stay-the-thousand-kyoto': [34.9869, 135.7585],
    'stay-hotel-granvia-kyoto': [34.9866, 135.7584],
    'stay-ekoin-koyasan': [34.2151, 135.5874],
    'stay-arima-grand': [34.7976, 135.2514],
    'stay-la-suite-kobe': [34.6871, 135.1881],
    'stay-mitsui-garden-otemachi': [35.6899, 139.7689],
    'stay-hotel-niwa-tokyo': [35.6995, 139.7526],
    'stay-airbnb-tokyo': [35.6812, 139.7671],
    'stay-disney-ambassador': [35.6267, 139.8841],
    'stay-disneyland-hotel': [35.6335, 139.8828],
    'stay-disney-celebration': [35.6498, 139.9068],
  },
  routing: {
    provider: 'google-directions',
    drivingProvider: 'google-directions',
    walkingProvider: 'google-directions',
    transitProvider: 'google-directions',
    googleApiKey: 'gapi:QUl6YVN5QkpB.Rmg0Mi15MF9p.czAtTnUteVNQ.UE5NUFptU01D.YnFN',
  },
  catalog: {
    activity: [
      {
        id: 'act-flight-dxb-arrival',
        city: 'work',
        label: '00:40 Arrive DXB (transit)',
        locked: true,
        url: 'https://www.dubaiairports.ae/',
        image: 'https://www.dubaiairports.ae/images/passengerslibraries/home-page/hero-slider/hero-slider-02.png',
        description:
          "Land in Dubai International Airport's bright Terminal 3 to begin the long-haul connection toward Japan. Use the brief layover to stretch, refuel, and make note of the departure gates for the overnight Emirates sector.",
      },
      {
        id: 'act-flight-dxb-kix',
        city: 'work',
        label: '03:05 DXB → KIX (EK316)',
        coord: 'kix',
        locked: true,
        url: 'https://www.emirates.com/english/destinations/flights-to-osaka/',
        image: 'https://c.ekstatic.net/shared/images/destination/v1/airports/KIX/1920x480.jpg',
        description:
          'Board Emirates flight EK316 from Dubai to Kansai International Airport with lie-flat seats and Japanese inflight dining. Expect a smooth overnight sector that positions you for a late-afternoon arrival in Osaka.',
      },
      {
        id: 'act-arrive-kix',
        city: 'work',
        label: '17:05 Arrive KIX',
        coord: 'kix',
        locked: true,
        url: 'https://www.kansai-airport.or.jp/en/',
        image: 'https://www.kansai-airport.or.jp/static/images/banner/kixguide/concierge_en.jpg',
        description:
          'Touch down at Kansai International Airport\'s man-made island terminal and breeze through automated arrivals. Pick up an IC transit card and freshen up before transferring toward Hirakata.',
      },
      {
        id: 'act-transfer-kix-hirakata',
        city: 'osaka',
        label: 'KIX → Hirakata (~90m)',
        coord: 'hirakatashi',
        url: 'https://www.kansai-airport.or.jp/en/access/train',
        image: 'https://www.kansai-airport.or.jp/static/images/access/train/railwaymap_en.png',
        description:
          'Ride the Haruka limited express and Keihan line for a relaxed ninety-minute hop from Kansai Airport to Hirakatashi Station. Keep luggage handy for the Tennoji transfer and enjoy bay views as the train swings inland.',
      },
      {
        id: 'act-dinner-nana',
        city: 'osaka',
        label: 'Dinner with Nana (Hirakata)',
        coord: 'hirakatashi',
        url: 'https://www.osaka-info.jp/en/areas/hirakata/',
        image: 'https://www.osaka-info.jp/common/img/gnav/gnav_osaka_food@2x.jpg',
        description:
          'Celebrate arrival with a relaxed izakaya dinner in Hirakata alongside Nana and sample seasonal Kansai dishes. Use the evening catch-up to review the week\'s plans and ease gently into Japan time.',
      },
      {
        id: 'act-transfer-hirakata-kix',
        city: 'work',
        label: 'Hirakata → KIX',
        coord: 'kix',
        url: 'https://www.kansai-airport.or.jp/en/access/limousine',
        image: 'https://www.kansai-airport.or.jp/static/images/banner/kixguide/dine.jpg',
        description:
          'Pack up for the return trip and take the early Keihan and JR services or limousine bus back to Kansai Airport. Leave buffer time for duty-free shopping and last-minute snacks before clearing security.',
      },
      {
        id: 'act-flight-kix-dxb',
        city: 'work',
        label: '23:10 KIX → DXB (EK317)',
        coord: 'kix',
        locked: true,
        url: 'https://www.emirates.com/english/destinations/flights-from-osaka/',
        image: 'https://c.ekstatic.net/shared/images/destination/v1/airports/DXB/1920x480.jpg',
        description:
          'Depart Kansai on Emirates EK317 for the overnight hop back to Dubai with time for a final bowl of udon in the lounge. Watch Osaka Bay fade beneath the wing as you settle in for a restful flight home.',
      },
      {
        id: 'act-dotonbori-walk',
        city: 'osaka',
        label: 'Dōtonbori walk + street food',
        coord: 'dotonbori',
        url: 'https://osaka-info.jp/en/discover/dotonbori/',
        image: 'https://www.osaka-info.jp/common/img/gnav/gnav_osaka_pop-culture@2x.jpg',
        description:
          'Follow the neon-lit Dōtonbori canal past takoyaki stalls, souvenir arcades, and the iconic Glico runner. Book tables at Mizuno and Kushikatsu Daruma to sample Osaka soul food between photo stops.',
        bookingIds: ['book-mizuno', 'book-daruma'],
      },
      {
        id: 'act-umeda-sky',
        city: 'osaka',
        label: 'Umeda Sky Building sunset',
        coord: 'umedaSky',
        url: 'https://www.skybldg.co.jp/en/',
        image: 'https://www.skybldg.co.jp/cmn/img/ogp.jpg',
        description:
          'Ride the floating escalators up the Umeda Sky Building for a golden-hour panorama over Osaka. Linger on the open-air rooftop deck as the Yodo River sparkles with city lights.',
        bookingIds: ['book-umeda-sky'],
      },
      {
        id: 'act-abeno-harukas',
        city: 'osaka',
        label: 'Abeno HARUKAS 300 view',
        coord: 'abenoHarukas',
        url: 'https://www.abenoharukas-300.jp/en/',
        image: 'https://www.abenoharukas-300.jp/en/images/composition_bg.jpg',
        description:
          "Ascend Japan's tallest skyscraper for floor-to-ceiling vistas stretching from Osaka Castle to Mount Ikoma. Pair the observatory visit with a stop at the museum shop and a coffee in the Sky Garden 300 lounge.",
        bookingIds: ['book-harukas'],
      },
      {
        id: 'act-karaoke-namba',
        city: 'osaka',
        label: 'Namba karaoke & late izakaya',
        coord: 'dotonbori',
        url: 'https://www.japan-guide.com/e/e4009.html',
        image: 'https://www.japan-guide.com/g24/4009_01.jpg',
        description:
          'Reserve a private karaoke booth in Namba for neon-drenched singalongs and endless drink refills. Close the night with kushikatsu skewers and highballs delivered straight from Daruma.',
        bookingIds: ['book-daruma'],
      },
      {
        id: 'guide-donki-night-run',
        city: 'osaka',
        label: 'Donki night run (Dōtonbori)',
        coord: 'dotonbori',
        url: 'https://www.donki.com/en/store/shop_detail.php?shop_id=154',
        image: 'https://www.donki.com/shared/img/store/st_store/154/2025071117522059070.jpg',
        description:
          'Dash through the multistory Don Quijote flagship for quirky souvenirs, cosmetics, and late-night snacks. Ride the canal-side ferris wheel and leave with armfuls of specialty KitKats and gachapon prizes.',
      },
      {
        id: 'event-midosuji-lights',
        city: 'osaka',
        label: 'Osaka Festival of the Lights — Midosuji',
        coord: 'midosujiIllumination',
        url: 'https://www.hikari-kyoen.com/en/',
        image: 'https://www.hikari-kyoen.com/img/common/ogp.png',
        description:
          "Stroll beneath illuminated gingko trees and projection-mapped facades along Osaka's grand Midosuji boulevard. Live choirs and pop-up cafés keep the festive energy high from Namba to Umeda.",
        bookingIds: ['book-midosuji-lights'],
      },
      {
        id: 'act-usj-day',
        city: 'osaka',
        label: 'Universal Studios Japan day',
        coord: 'usj',
        url: 'https://www.usj.co.jp/web/en/us',
        image: 'https://www.usj.co.jp/img/usj_ogp.png',
        description:
          'Spend a full day conquering Universal Studios Japan from Super Nintendo World to the Wizarding World. Stack Express Pass windows to breeze between coasters, stage shows, and seasonal parades.',
        bookingIds: ['book-usj'],
      },
      {
        id: 'act-arashiyama',
        city: 'kyoto',
        label: 'Arashiyama bamboo grove & river',
        coord: 'arashiyama',
        url: 'https://www.japan-guide.com/e/e3912.html',
        image: 'https://www.japan-guide.com/g18/3912_top.jpg',
        description:
          'Hop aboard the Sagano Romantic Train for river views before wandering Arashiyama\'s bamboo grove and Togetsukyo Bridge. Rent bikes or a rowboat to explore temples and maple-filled backstreets at your own pace.',
        bookingIds: ['book-sagano'],
      },
      {
        id: 'act-kiyomizudera',
        city: 'kyoto',
        label: 'Kiyomizu-dera & Sannenzaka',
        coord: 'kiyomizudera',
        url: 'https://www.kiyomizudera.or.jp/en/',
        image: 'https://www.kiyomizudera.or.jp/en/img/common/ogp/ogp.jpg',
        description:
          'Climb the lantern-lined lanes of Higashiyama to Kiyomizu-dera\'s wooden stage overlooking Kyoto. Browse pottery studios on Sannenzaka and toast with matcha before descending at sunset.',
        bookingIds: ['book-kiyomizu-night'],
      },
      {
        id: 'act-fushimi-inari',
        city: 'kyoto',
        label: 'Fushimi Inari at dusk',
        coord: 'fushimiInari',
        url: 'https://inari.jp/en/',
        image: 'https://inari.jp/en/wp-content/uploads/2021/10/index_about.jpg',
        description:
          'Hike the seemingly endless tunnels of vermilion torii gates at Fushimi Inari as lanterns flicker on. Pause at quiet sub-shrines for fox ema and sweeping views across Kyoto basin.',
      },
      {
        id: 'act-uji-tea',
        city: 'kyoto',
        label: 'Uji tea tastings & Byōdō-in stroll',
        coord: 'uji',
        url: 'https://matcha-jp.com/en/1155',
        image: 'https://resources.matcha-jp.com/original/2018/11/30-67134.png',
        description:
          'Travel to Uji for hand-whisked matcha tastings along the approach to Byōdō-in Temple. Join a small-group tea ceremony to grind tencha, savor wagashi, and learn the rituals of Ujicha service.',
        bookingIds: ['book-tea-ceremony'],
      },
      {
        id: 'act-nara-park',
        city: 'kyoto',
        label: 'Nara Park deer + Tōdai-ji',
        coord: 'naraPark',
        url: 'https://www.visitnara.jp/destinations/nara-city/nara-park/',
        image: 'https://images.contentful.com/9uvqwr58loxx/2Nc75AbOM8S6muQM2iAEOS/424eef0184a4b37f48d67cfdd22df286/PMH_160814_194534_1319.jpg?fit=thumb&w=1300&h=800&q=70',
        description:
          "Spend a gentle morning feeding senbei to Nara's bowing deer before visiting the Great Buddha at Tōdai-ji. Wander Kasuga Taisha's lantern-lined forest paths and sample persimmon-leaf sushi on Sanjo-dori.",
      },
      {
        id: 'act-koyasan-okunoin',
        city: 'kyoto',
        label: 'Kōyasan Okunoin night walk',
        coord: 'okunoin',
        url: 'https://www.koyasan.or.jp/en/meguru/spot/okunoin/',
        image: 'https://www.koyasan.or.jp/images/og_image.jpg',
        description:
          'Join a monk-guided night walk through Okunoin\'s cedar forest to the Torodo lantern hall and Kobo Daishi\'s mausoleum. Hear centuries-old legends as mossy gravestones glow softly in the dark.',
      },
      {
        id: 'guide-kimono-stroll',
        city: 'kyoto',
        label: 'Kimono stroll photo spot',
        coord: 'kiyomizudera',
        url: 'https://www.yumeyakata.com/',
        image: 'https://www.kyoto.yumeyakata.com/common/img/top/top-main-kimono-summer-2025.jpg',
        description:
          'Rent seasonal kimono or hakama, complete with hairstyling, before wandering Kyoto\'s preserved lanes. Pose beneath paper lanterns and pagoda backdrops while the studio stores your day bag.',
        bookingIds: ['book-kimono'],
      },
      {
        id: 'event-kiyomizu-lightup',
        city: 'kyoto',
        label: 'Kiyomizu-dera autumn night illumination',
        coord: 'kiyomizudera',
        url: 'https://www.kiyomizudera.or.jp/en/event/',
        image: 'https://www.kiyomizudera.or.jp/en/img/common/ogp/ogp.jpg',
        description:
          "Return after dark for Kiyomizu-dera's limited autumn illumination with a cobalt beam stretching across Kyoto. Glide along the verandas to watch fiery maples reflected in the temple ponds.",
        bookingIds: ['book-kiyomizu-night'],
      },
      {
        id: 'event-eikando-lightup',
        city: 'kyoto',
        label: 'Eikando Zenrinji maple light-up',
        coord: 'eikando',
        url: 'https://eikando.or.jp/',
        image: 'https://eikando.or.jp/photo_image/video_frame2509.jpg',
        description:
          'Marvel at Eikandō\'s mirror-still pond and scarlet momiji during the evening illumination. Expect timed entry and enjoy the hillside terrace view before following lantern paths back toward Nanzen-ji.',
        bookingIds: ['book-eikando-night'],
      },
      {
        id: 'event-rurikoin-autumn',
        city: 'kyoto',
        label: 'Rurikō-in autumn garden visit',
        coord: 'rurikoin',
        url: 'https://rurikoin.komyoji.com/en/',
        image: 'https://rurikoin.komyoji.com/assets/images/top_Img04.jpg',
        description:
          "Admire Rurikō-in's famous tatami reflections of crimson maples and mountain scenery. The reservation-only visit includes a slow tour of the mossy garden and a seasonal tea service.",
        bookingIds: ['book-rurikoin'],
      },
      {
        id: 'act-arima-onsen',
        city: 'kobe',
        label: 'Arima Onsen golden & silver baths',
        coord: 'arimaOnsen',
        url: 'https://visit.arima-onsen.com/en/',
        image: 'https://visit.arima-onsen.com/shared/images/common/ogimage.png',
        description:
          'Soak in Arima Onsen\'s famous gold and silver mineral springs, alternating between open-air rotenburo and hinoki tubs. Wander the steep village lanes afterward for carbonated senbei and local crafts.',
      },
      {
        id: 'act-himeji-castle',
        city: 'kobe',
        label: 'Himeji Castle + Kōko-en',
        coord: 'himejiCastle',
        url: 'https://www.himejicastle.jp/en/',
        image: 'http://www.himejicastle.jp/ogp.png',
        description:
          'Climb the wooden towers of UNESCO-listed Himeji Castle for sweeping views of the white heron keep. Pair the visit with a tea break inside Kōko-en\'s landscaped garden rooms.',
        bookingIds: ['book-himeji'],
      },
      {
        id: 'act-harborland-night',
        city: 'kobe',
        label: 'Kobe Harborland evening lights',
        coord: 'harborland',
        url: 'https://www.feel-kobe.jp/en/sightseeing/spot/?sid=250',
        image: 'https://www.feel-kobe.jp/en/wp-content/themes/feel-kobe-plus/common/img/common/things_nature_pic01.jpg',
        description:
          "Catch the sunset from Kobe Harborland's Mosaic promenade with ferris wheel views over the bay. Cap the night with a harbor cruise or Kobe beef dinner overlooking the illuminated port tower.",
      },
      {
        id: 'act-disney-day',
        city: 'tokyo',
        label: 'Tokyo Disney day (Sea/Land)',
        coord: 'disneyResort',
        url: 'https://www.tokyodisneyresort.jp/en/',
        image: 'https://www.tokyodisneyresort.jp/tdrblog/wp-content/uploads/2023/03/0315_1-1024x576.jpg',
        description:
          "Split your time between Tokyo Disneyland classics and DisneySea's nautical worlds for a full resort immersion. Use the official app to secure priority access and stay for the Dreamlights parade.",
        bookingIds: ['book-tokyo-disney'],
      },
      {
        id: 'act-teamlab-planets',
        city: 'tokyo',
        label: 'teamLab Planets experience',
        coord: 'teamlabPlanets',
        url: 'https://teamlabplanets.dmm.com/en/',
        image: 'https://teamlabplanets.dmm.com/img/seo/thumbnail.jpg',
        description:
          "Wade barefoot through teamLab Planets' mirrored cosmos, water rooms, and floating flower garden in Toyosu. Allow extra time for the digital koi that react to every ripple of your movement.",
        bookingIds: ['book-teamlab-planets'],
      },
      {
        id: 'act-ghibli-museum',
        city: 'tokyo',
        label: 'Ghibli Museum (Mitaka)',
        coord: 'ghibliMuseum',
        url: 'https://www.ghibli-museum.jp/en/',
        image: 'https://www.ghibli-museum.jp/en/img/ghibli-museum.png',
        description:
          "Step inside Hayao Miyazaki's whimsical sketches, exclusive short films, and rooftop Laputa robot at the Ghibli Museum. Lawson-timed tickets keep crowds light so you can linger in the Straw Hat Café.",
        bookingIds: ['book-ghibli'],
      },
      {
        id: 'act-collab-cafe',
        city: 'tokyo',
        label: 'Collab café crawl (Animate/SQEX)',
        coord: 'sunshine60',
        url: 'https://cafe.animate.co.jp/',
        image: 'https://cafe.animate.co.jp/images/ogp.png',
        description:
          "Hop between Ikebukuro's rotating collaboration cafés for themed parfaits, exclusive coasters, and merch drops. Check reservation lotteries in advance to secure seats for the latest anime tie-ins.",
      },
      {
        id: 'act-shibuya-scramble',
        city: 'tokyo',
        label: 'Shibuya scramble + PARCO run',
        coord: 'shibuyaParco',
        url: 'https://www.japan-guide.com/e/e3007.html',
        image: 'https://www.japan-guide.com/g18/3007_01.jpg',
        description:
          "Surge across the world-famous Shibuya Scramble before exploring PARCO's pop-culture floors and rooftop park. Ride the elevator to Shibuya SKY for a helipad panorama over Tokyo's neon canyon.",
        bookingIds: ['book-shibuya-sky'],
      },
      {
        id: 'act-harajuku-fashion',
        city: 'tokyo',
        label: 'Harajuku fashion lanes',
        coord: 'takeshitaStreet',
        url: 'https://www.gotokyo.org/en/spot/257/index.html',
        image: 'https://www.gotokyo.org/shared/site_gotokyo_rn/images/ogp/ogp.png',
        description:
          'Browse Takeshita Street for lolita boutiques, vintage treasures, and rainbow crepes before drifting down Cat Street. Refuel with gyukatsu or fluffy pancakes between boutique hopping.',
        bookingIds: ['book-gyukatsu'],
      },
      {
        id: 'act-ikebukuro-day',
        city: 'tokyo',
        label: 'Ikebukuro Sunshine & otaku stops',
        coord: 'sunshine60',
        url: 'https://www.sunshinecity.co.jp/en/',
        image: 'https://sunshinecity.jp/themes/sunshine/resource/common/images/ogp_koushiki.png',
        description:
          "Devote a day to Sunshine City's Sky Circus, Pokémon Center Mega Tokyo, and VR experiences at Namja Town. Wander Otome Road for doujinshi finds and cap the night with Animate's newest releases.",
      },
      {
        id: 'act-karaoke-friends',
        city: 'tokyo',
        label: 'Late karaoke & izakaya with crew',
        coord: 'shibuyaParco',
        url: 'https://www.pasela.co.jp/en/',
        image: 'https://www.pasela.co.jp/images_2024r/shop/common/slide/top_slide_shibuya_img01.webp',
        description:
          'Reserve a large karaoke suite for the full crew and queue up anime anthems until the first train. Share highballs, honey toast, and late-night izakaya plates delivered straight to the room.',
      },
      {
        id: 'guide-shibuya-sky',
        city: 'tokyo',
        label: 'Shibuya SKY (observation deck)',
        coord: 'shibuyaParco',
        url: 'https://www.shibuya-scramble-square.com/en/sky/',
        image: 'https://www.shibuya-scramble-square.com/assets/img/og-img.jpg',
        description:
          "Secure timed tickets to Shibuya SKY's rooftop helipad for a 360-degree Tokyo skyline experience. Arrive thirty minutes before sunset to capture the scramble intersection glowing below.",
        bookingIds: ['book-shibuya-sky'],
      },
      {
        id: 'guide-omotesando-cafes',
        city: 'tokyo',
        label: 'Omotesandō cafés & boutiques',
        coord: 'takeshitaStreet',
        url: 'https://www.timeout.com/tokyo/restaurants/the-best-cafes-in-omotesando',
        image: 'https://media.timeout.com/images/106307650/750/422/image.jpg',
        description:
          'Spend an easy afternoon café-hopping along tree-lined Omotesandō between Kengo Kuma-designed boutiques. Sample pour-over coffee, delicate pastries, and hidden basement roasters between shopping stops.',
      },
      {
        id: 'guide-nintendo-parco',
        city: 'tokyo',
        label: 'Nintendo Tokyo & Pokémon Center',
        coord: 'shibuyaParco',
        url: 'https://www.nintendo.co.jp/officialstore/en/',
        image: 'https://www.nintendo.com/jp/img/og_nintendo.png',
        description:
          'Queue early for the Nintendo Tokyo and Pokémon Center Shibuya floors packed with exclusive merch and interactive displays. Rotate through neighboring Jump, Capcom, and eSports stores for more limited drops.',
      },
      {
        id: 'guide-animate-ikebukuro',
        city: 'tokyo',
        label: 'Animate Ikebukuro flagship',
        coord: 'animateIkebukuro',
        url: 'https://www.animate.co.jp/shop/ikebukuro/',
        image: 'https://www.animate.co.jp/assets/img/ogp/ikebukuro.jpg?2024-06-10',
        description:
          'Navigate the multi-level Animate Ikebukuro flagship for fresh manga, drama CDs, and BL exclusives. Check the event floors for autograph sessions and limited-edition pop-up exhibits.',
      },
      {
        id: 'guide-akihabara-arcades',
        city: 'tokyo',
        label: 'Akihabara retro arcades crawl',
        coord: 'akihabara',
        url: 'https://www.gotokyo.org/en/destinations/northern-tokyo/akihabara/index.html',
        image: 'https://www.gotokyo.org/shared/site_gotokyo_rn/images/ogp/ogp.png',
        description:
          'Dive into Akihabara\'s multi-story arcades for rhythm games, crane prizes, and retro cabinets. Trade 100-yen coins for plays at Taito Station, GiGO, and Club Sega before wandering electric-town alleys.',
      },
      {
        id: 'guide-harajuku-vintage',
        city: 'tokyo',
        label: 'Harajuku thrift & vintage run',
        coord: 'harajukuVintage',
        url: 'https://www.timeout.com/tokyo/shopping/harajuku-vintage-shops',
        image: 'https://media.timeout.com/images/106307650/750/422/image.jpg',
        description:
          "Map out Harajuku's top vintage shops like Ragtag, Chicago, and Kinji for one-of-a-kind finds. Hunt for varsity jackets and reworked kimono pieces before rewarding yourself with gyukatsu.",
        bookingIds: ['book-gyukatsu'],
      },
      {
        id: 'event-roppongi-illumination',
        city: 'tokyo',
        label: 'Tokyo Midtown Roppongi illuminations',
        coord: 'roppongiMidtown',
        url: 'https://www.tokyo-midtown.com/en/event/xmas/',
        image: 'https://en.tokyo-midtown.com/assets/images/ogp.png',
        description:
          "Witness Tokyo Midtown's Starlight Garden where synchronized LEDs blanket the lawn in cosmic hues. Sip mulled wine at the Christmas market and stroll the sparkling Keyakizaka terrace.",
        bookingIds: ['book-midtown-christmas'],
      },
      {
        id: 'event-blue-cave',
        city: 'tokyo',
        label: 'Shibuya Ao no Dokutsu (Blue Cave)',
        coord: 'shibuyaParco',
        url: 'https://www.gotokyo.org/en/spot/ev082/index.html',
        image: 'https://www.gotokyo.org/en/spot/ev082/images/ev082_gd10121_main.webp',
        description:
          "Walk beneath the Blue Cave illumination as thousands of LEDs wash Shibuya's zelkova trees in sapphire light. Ambient music and gentle snow machines create ethereal winter photo ops.",
        bookingIds: ['book-blue-cave'],
      },
    ],
    stay: [
      {
        id: 'stay-candeo-hirakata',
        city: 'osaka',
        label: 'Candeo Hotels Osaka Hirakata',
        url: 'https://www.candeohotels.com/en/osaka-hirakata/',
        coord: 'stay-candeo-hirakata',
        image: 'https://www.candeohotels.com/en/assets_c/2024/01/hirakata_main_kv-thumb-2560x1774-18748.jpg',
        description:
          'Check into Candeo Hirakata for modern business-class rooms, Sky Spa baths, and a hearty Japanese-Western breakfast buffet. The hotel sits steps from Hirakatashi Station for quick Keihan Line hops into Osaka or Kyoto.',
        bookingIds: ['book-candeo-hirakata'],
      },
      {
        id: 'stay-sunplaza-hirakata',
        city: 'osaka',
        label: 'Hirakata SunPlaza Hotel',
        url: 'https://sunplazahotel.co.jp/en/',
        coord: 'stay-sunplaza-hirakata',
        image: 'https://sunplazahotel.co.jp/en/img/slide/1.jpg',
        description:
          'This classic business hotel offers compact ensuite rooms, on-site laundry, and friendly staff used to international guests. It is directly across from Hirakatashi Station, making late arrivals and early departures painless.',
        bookingIds: ['book-sunplaza-hirakata'],
      },
      {
        id: 'stay-cross-hotel-osaka',
        city: 'osaka',
        label: 'Cross Hotel Osaka',
        url: 'https://cross-osaka.orixhotelsandresorts.com/en/',
        coord: 'stay-cross-hotel-osaka',
        image: 'https://cross-osaka.orixhotelsandresorts.com/_assets/images/common/ogp.jpg',
        description:
          'Boutique rooms at Cross Hotel mix bold lighting with soaking tubs just off the Dōtonbori canal. Guests receive priority at the connected restaurants and easy access to the neon nightlife of Shinsaibashi and Namba.',
        bookingIds: ['book-cross-hotel-osaka'],
      },
      {
        id: 'stay-the-thousand-kyoto',
        city: 'kyoto',
        label: 'THE THOUSAND KYOTO',
        url: 'https://www.keihanhotels-resorts.co.jp/the-thousand-kyoto/en/',
        coord: 'stay-the-thousand-kyoto',
        image: 'https://www.keihanhotels-resorts.co.jp/the-thousand-kyoto/assets/images/ogp.png',
        description:
          'Minimalist suites combine tatami accents with deep hinoki baths just steps from Kyoto Station\'s central exit. The property features a serene spa, tea lounge, and concierge team skilled at securing temple reservations.',
        bookingIds: ['book-the-thousand-kyoto'],
      },
      {
        id: 'stay-hotel-granvia-kyoto',
        city: 'kyoto',
        label: 'Hotel Granvia Kyoto',
        url: 'https://www.granviakyoto.com/',
        coord: 'stay-hotel-granvia-kyoto',
        image: 'https://www.granviakyoto.com/parts_top_mv/assets_c/2020/03/db_mv_02-thumb-autox412-1157.jpg',
        description:
          'Perched above Kyoto Station, Hotel Granvia delivers spacious rooms, indoor pool access, and unbeatable rail connections. Upper floors capture skyline views while the lobby hosts seasonal art installations.',
        bookingIds: ['book-hotel-granvia-kyoto'],
      },
      {
        id: 'stay-ekoin-koyasan',
        city: 'kyoto',
        label: 'Kōyasan Eko-in temple stay',
        url: 'https://www.ekoin.jp/en/',
        coord: 'stay-ekoin-koyasan',
        image: 'https://www.ekoin.jp/wp-content/uploads/2021/11/twitter_card.jpg',
        description:
          'Sleep on tatami floors at the 1,100-year-old Eko-in, where monks serve vegan shōjin ryōri dinners and lead morning prayers. Guests can join meditation workshops and lantern-lit night tours through nearby Okunoin.',
        bookingIds: ['book-ekoin-koyasan'],
      },
      {
        id: 'stay-arima-grand',
        city: 'kobe',
        label: 'Arima Grand Hotel',
        url: 'https://www.arima-gh.jp/en/',
        coord: 'stay-arima-grand',
        image: 'https://www.arima-gh.jp/wp-content/themes/arimagh/images/common/ogp.jpg',
        description:
          'This hilltop ryokan overlooks Arima Onsen with both gold and silver hot-spring baths plus seasonal kaiseki dinners. Shuttle buses connect guests to the station, and panorama lounges frame the Rokko mountains.',
        bookingIds: ['book-arima-grand'],
      },
      {
        id: 'stay-la-suite-kobe',
        city: 'kobe',
        label: 'Hotel La Suite Kobe Harborland',
        url: 'https://www.l-s.jp/english/',
        coord: 'stay-la-suite-kobe',
        image: 'https://www.l-s.jp/common/img/thumb_fb.png',
        description:
          'Every room at La Suite Kobe includes a balcony facing the port, whirlpool bath, and L’Occitane amenities. Walk downstairs for patisserie treats before sunset cruises across Kobe Harborland.',
        bookingIds: ['book-la-suite-kobe'],
      },
      {
        id: 'stay-mitsui-garden-otemachi',
        city: 'tokyo',
        label: 'Mitsui Garden Hotel Otemachi',
        url: 'https://www.gardenhotels.co.jp/otemachi/eng/',
        coord: 'stay-mitsui-garden-otemachi',
        image: 'https://www.gardenhotels.co.jp/assets/images/otemachi/home/mv-eng-pc-01.jpg',
        description:
          'A calm hideaway north of Tokyo Station, Mitsui Garden Otemachi blends modern Japanese décor with a soothing public bath. Grab free bikes to explore Nihonbashi or hop the Marunouchi Line from the nearby station.',
        bookingIds: ['book-mitsui-garden-otemachi'],
      },
      {
        id: 'stay-hotel-niwa-tokyo',
        city: 'tokyo',
        label: 'Hotel Niwa Tokyo',
        url: 'https://www.hotelniwa.jp/en/',
        coord: 'stay-hotel-niwa-tokyo',
        image: 'https://www.hotelniwa.jp/assets/img/common/ogp.png',
        description:
          'Hotel Niwa layers warm wood, courtyard gardens, and pillow menus for a boutique stay near Suidobashi Station. Amenities include a 24-hour gym, coin laundry, and staff who can secure dinner reservations.',
        bookingIds: ['book-hotel-niwa-tokyo'],
      },
      {
        id: 'stay-airbnb-tokyo',
        city: 'tokyo',
        label: 'Airbnb — central Tokyo flat',
        url: 'https://www.airbnb.com/s/Tokyo--Japan/homes',
        coord: 'stay-airbnb-tokyo',
        image: 'https://a0.muscache.com/im/pictures/fe7217ff-0b24-438d-880d-b94722c75bf5.jpg',
        description:
          'Opt for a central Tokyo Airbnb to gain extra living space, a kitchenette, and flexible self-check-in. Filter for listings near JR Yamanote stations to simplify meetups with friends and late-night returns.',
        bookingIds: ['book-airbnb-tokyo'],
      },
      {
        id: 'stay-disney-ambassador',
        city: 'tokyo',
        label: 'Disney Ambassador Hotel',
        url: 'https://www.disneyhotels.jp/dh/en/',
        coord: 'stay-disney-ambassador',
        image: 'https://www.disneyhotels.jp/dh/en/images/ogp.png',
        description:
          'The art-deco Disney Ambassador features character rooms, chef Mickey breakfasts, and exclusive park entry privileges. A dedicated shuttle connects directly to both Tokyo Disneyland and DisneySea gates.',
        bookingIds: ['book-disney-ambassador'],
      },
      {
        id: 'stay-disneyland-hotel',
        city: 'tokyo',
        label: 'Tokyo Disneyland Hotel',
        url: 'https://www.disneyhotels.jp/tdh/en/',
        coord: 'stay-disneyland-hotel',
        image: 'https://www.disneyhotels.jp/tdh/en/images/ogp.png',
        description:
          'Victorian-style suites sit right at the entrance to Tokyo Disneyland with whimsical décor and soaking tubs. Guests enjoy priority check-in, in-room amenities themed to Disney classics, and monorail proximity.',
        bookingIds: ['book-disneyland-hotel'],
      },
      {
        id: 'stay-disney-celebration',
        city: 'tokyo',
        label: 'Tokyo Disney Celebration Hotel',
        url: 'https://www.disneyhotels.jp/dch/en/',
        coord: 'stay-disney-celebration',
        image: 'https://www.disneyhotels.jp/dch/images/ogp.png',
        description:
          'Stay at Celebration Hotel for colorful storybook rooms, complimentary breakfast, and free shuttles to the resort area. It is the most budget-friendly Disney-branded option while preserving early park entry perks.',
        bookingIds: ['book-disney-celebration'],
      },
    ],
    booking: [
      { id: 'book-usj', city: 'osaka', label: 'USJ + Super Nintendo World tickets', url: 'https://www.usj.co.jp/e/ticket/' },
      { id: 'book-umeda-sky', city: 'osaka', label: 'Umeda Sky Building tickets', url: 'https://www.skybldg.co.jp/en/' },
      { id: 'book-harukas', city: 'osaka', label: 'Abeno HARUKAS 300 observatory', url: 'https://www.abenoharukas-300.jp/en/' },
      { id: 'book-midosuji-lights', city: 'osaka', label: 'Osaka Festival of the Lights info', url: 'https://www.hikari-kyoen.com/en/' },
      { id: 'book-mizuno', city: 'osaka', label: 'Okonomiyaki Mizuno reservations', url: 'https://www.gltjp.com/en/directory/item/12081/' },
      { id: 'book-daruma', city: 'osaka', label: 'Kushikatsu Daruma (Shinsekai)', url: 'https://www.dotonbori.or.jp/en/shops/68' },
      { id: 'book-sagano', city: 'kyoto', label: 'Sagano Romantic Train tickets', url: 'https://www.sagano-kanko.co.jp/en/ticket/' },
      { id: 'book-kimono', city: 'kyoto', label: 'Kyoto kimono rental (Yumeyakata)', url: 'https://www.yumeyakata.com/' },
      { id: 'book-tea-ceremony', city: 'kyoto', label: 'Camellia tea ceremony booking', url: 'https://www.tea-kyoto.com/' },
      { id: 'book-kiyomizu-night', city: 'kyoto', label: 'Kiyomizu-dera night illumination', url: 'https://www.kiyomizudera.or.jp/en/event/' },
      { id: 'book-eikando-night', city: 'kyoto', label: 'Eikando maple light-up details', url: 'https://eikando.or.jp/' },
      { id: 'book-rurikoin', city: 'kyoto', label: 'Rurikō-in autumn visit info', url: 'https://rurikoin.komyoji.com/en/' },
      { id: 'book-himeji', city: 'kobe', label: 'Himeji Castle timed tickets', url: 'https://himejicastle.ntaticketing.com/' },
      { id: 'book-kobe-ropeway', city: 'kobe', label: 'Kobe Nunobiki Ropeway', url: 'https://www.kobeherb.com/en/ropeway/' },
      { id: 'book-teamlab-planets', city: 'tokyo', label: 'teamLab Planets tickets', url: 'https://teamlabplanets.dmm.com/en' },
      { id: 'book-teamlab-borderless', city: 'tokyo', label: 'teamLab Borderless (Azabudai Hills)', url: 'https://www.teamlab.art/e/borderless/' },
      { id: 'book-tokyo-disney', city: 'tokyo', label: 'Tokyo Disney Resort tickets', url: 'https://www.tokyodisneyresort.jp/en/ticket/' },
      { id: 'book-ghibli', city: 'tokyo', label: 'Ghibli Museum via Lawson', url: 'https://l-tike.com/st1/ghibli-en/' },
      { id: 'book-shibuya-sky', city: 'tokyo', label: 'Shibuya SKY admission', url: 'https://www.shibuya-scramble-square.com/en/sky/' },
      { id: 'book-blue-cave', city: 'tokyo', label: 'Ao no Dokutsu (Blue Cave) info', url: 'https://bluecavetokyo.com/' },
      { id: 'book-midtown-christmas', city: 'tokyo', label: 'Tokyo Midtown Christmas lights', url: 'https://www.tokyo-midtown.com/en/event/xmas/' },
      { id: 'book-uogashi', city: 'tokyo', label: 'Standing sushi Uogashi (Shibuya)', url: 'https://www.timeout.com/tokyo/restaurants/uogashi-nihon-ichi-shibuya-dogenzaka' },
      { id: 'book-gyukatsu', city: 'tokyo', label: 'Gyukatsu Motomura Harajuku', url: 'https://s.tabelog.com/en/tokyo/A1306/A130601/13208866/' },
      { id: 'book-candeo-hirakata', city: 'osaka', label: 'Candeo Hirakata reservations', url: 'https://www.candeohotels.com/en/osaka-hirakata/reservation/' },
      { id: 'book-sunplaza-hirakata', city: 'osaka', label: 'Hirakata SunPlaza booking', url: 'https://booking.sunplazahotel.co.jp/' },
      { id: 'book-cross-hotel-osaka', city: 'osaka', label: 'Cross Hotel Osaka offers', url: 'https://www.crosshotel.com/osaka/en/stay/' },
      { id: 'book-the-thousand-kyoto', city: 'kyoto', label: 'THE THOUSAND KYOTO stays', url: 'https://www.keihanhotels-resorts.co.jp/the-thousand-kyoto/en/stay/' },
      { id: 'book-hotel-granvia-kyoto', city: 'kyoto', label: 'Hotel Granvia Kyoto booking', url: 'https://www.granviakyoto.com/rooms/' },
      { id: 'book-ekoin-koyasan', city: 'kyoto', label: 'Eko-in temple stay booking', url: 'https://www.ekoin.jp/en/reservation/' },
      { id: 'book-arima-grand', city: 'kobe', label: 'Arima Grand Hotel plans', url: 'https://www.arima-gh.jp/en/stay/' },
      { id: 'book-la-suite-kobe', city: 'kobe', label: 'La Suite Kobe reservations', url: 'https://www.l-s.jp/english/reservation/' },
      { id: 'book-mitsui-garden-otemachi', city: 'tokyo', label: 'Mitsui Garden Otemachi booking', url: 'https://www.gardenhotels.co.jp/otemachi/eng/room/' },
      { id: 'book-hotel-niwa-tokyo', city: 'tokyo', label: 'Hotel Niwa Tokyo offers', url: 'https://www.hotelniwa.jp/en/rooms/' },
      { id: 'book-airbnb-tokyo', city: 'tokyo', label: 'Airbnb Tokyo listings', url: 'https://www.airbnb.com/s/Tokyo--Japan/homes' },
      { id: 'book-disney-ambassador', city: 'tokyo', label: 'Disney Ambassador reservations', url: 'https://reserve.tokyodisneyresort.jp/en/hotel/dh/' },
      { id: 'book-disneyland-hotel', city: 'tokyo', label: 'Tokyo Disneyland Hotel booking', url: 'https://reserve.tokyodisneyresort.jp/en/hotel/tdh/' },
      { id: 'book-disney-celebration', city: 'tokyo', label: 'Disney Celebration Hotel booking', url: 'https://reserve.tokyodisneyresort.jp/en/hotel/dch/' },
    ],
  },
  prefill: {
    '2025-11-14': {
      loc: 'work',
      theme: 'Flights → Osaka',
      friends: ['Nana'],
      stay: 'stay-candeo-hirakata',
      slots: {
        morning: ['act-flight-dxb-arrival'],
        afternoon: ['act-flight-dxb-kix'],
        evening: ['act-arrive-kix', 'act-transfer-kix-hirakata', 'act-dinner-nana'],
      },
      locks: {
        'act-flight-dxb-arrival': 1,
        'act-flight-dxb-kix': 1,
        'act-arrive-kix': 1,
      },
    },
    '2025-11-15': {
      loc: 'kyoto',
      theme: 'Kyoto sights',
      friends: ['Nana'],
      stay: null,
      slots: {
        morning: ['act-arashiyama'],
        afternoon: ['act-kiyomizudera'],
        evening: ['act-fushimi-inari'],
      },
      locks: {},
    },
    '2025-11-16': {
      loc: 'kyoto',
      theme: 'Nara or Uji',
      friends: ['Nana'],
      stay: null,
      slots: {
        morning: ['act-nara-park'],
        afternoon: ['act-uji-tea'],
        evening: [],
      },
      locks: {},
    },
    '2025-11-17': {
      loc: 'kyoto',
      theme: 'Kōyasan overnight',
      friends: ['Nana'],
      stay: 'stay-ekoin-koyasan',
      slots: {
        morning: [],
        afternoon: ['act-koyasan-okunoin'],
        evening: ['act-koyasan-okunoin'],
      },
      locks: {},
    },
    '2025-11-18': {
      loc: 'work',
      theme: 'Tue — Nana work',
      friends: ['Nana'],
      stay: null,
      slots: {
        morning: [],
        afternoon: [],
        evening: ['act-dotonbori-walk'],
      },
      locks: {},
    },
    '2025-11-19': {
      loc: 'kobe',
      theme: 'Arima Onsen + Kobe night',
      friends: ['Nana'],
      stay: 'stay-arima-grand',
      slots: {
        morning: ['act-arima-onsen'],
        afternoon: ['act-harborland-night'],
        evening: [],
      },
      locks: {},
    },
    '2025-11-20': {
      loc: 'osaka',
      theme: 'Umeda sunset + karaoke',
      friends: ['Nana'],
      stay: null,
      slots: {
        morning: [],
        afternoon: ['act-umeda-sky'],
        evening: ['act-karaoke-namba'],
      },
      locks: {},
    },
    '2025-11-21': {
      loc: 'work',
      theme: 'Fri — Nana work',
      friends: ['Nana'],
      stay: null,
      slots: {
        morning: [],
        afternoon: [],
        evening: ['act-abeno-harukas'],
      },
      locks: {},
    },
    '2025-11-22': {
      loc: 'tokyo',
      theme: 'Disney or teamLab',
      friends: ['Nana'],
      stay: 'stay-disneyland-hotel',
      slots: {
        morning: ['act-disney-day'],
        afternoon: ['act-disney-day'],
        evening: ['act-disney-day'],
      },
      locks: {},
    },
    '2025-11-23': {
      loc: 'tokyo',
      theme: 'Nicole + Ken day',
      friends: ['Nicole', 'Ken', 'James'],
      stay: 'stay-airbnb-tokyo',
      slots: {
        morning: ['act-teamlab-planets'],
        afternoon: ['act-collab-cafe'],
        evening: ['act-karaoke-friends'],
      },
      locks: {},
    },
    '2025-11-24': {
      loc: 'tokyo',
      theme: 'Shibuya / Harajuku',
      friends: ['Nicole', 'Ken', 'James', 'Phil'],
      stay: 'stay-airbnb-tokyo',
      slots: {
        morning: ['act-shibuya-scramble'],
        afternoon: ['act-harajuku-fashion'],
        evening: ['act-ikebukuro-day'],
      },
      locks: {},
    },
    '2025-11-25': {
      loc: 'work',
      theme: 'Tue — Travel/admin',
      friends: ['Nana'],
      stay: null,
      slots: {
        morning: [],
        afternoon: [],
        evening: [],
      },
      locks: {},
    },
    '2025-11-26': {
      loc: 'kobe',
      theme: 'Himeji Castle day',
      friends: [],
      stay: null,
      slots: {
        morning: ['act-himeji-castle'],
        afternoon: [],
        evening: [],
      },
      locks: {},
    },
    '2025-11-27': {
      loc: 'kobe',
      theme: 'Easy Kansai',
      friends: [],
      stay: null,
      slots: {
        morning: ['act-harborland-night'],
        afternoon: [],
        evening: [],
      },
      locks: {},
    },
    '2025-11-28': {
      loc: 'osaka',
      theme: 'Birthday in Osaka',
      friends: ['Nana', 'Nicole', 'Ken', 'James'],
      stay: null,
      slots: {
        morning: [],
        afternoon: [],
        evening: ['act-karaoke-namba'],
      },
      locks: {},
    },
    '2025-11-29': {
      loc: 'kyoto',
      theme: 'Leaves & tea',
      friends: ['Nana'],
      stay: null,
      slots: {
        morning: ['act-uji-tea'],
        afternoon: ['act-arashiyama'],
        evening: [],
      },
      locks: {},
    },
    '2025-11-30': {
      loc: 'work',
      theme: 'Fly home',
      friends: ['Nana'],
      stay: null,
      slots: {
        morning: ['act-transfer-hirakata-kix'],
        afternoon: [],
        evening: ['act-flight-kix-dxb'],
      },
      locks: {
        'act-flight-kix-dxb': 1,
      },
    },
  },
};
