from typing import Any, Dict, List


ITINERARY_DAYS: List[Dict[str, Any]] = [
    {
        "date": "2025-11-14",
        "weekday": "Friday",
        "title": "Touchdown & cosy Hirakata welcome",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "Arrive at KIX, settle into the Keihan-line base, and keep the first night gentle "
        "with Nana after work.",
        "nanako_work": True,
        "friends": "Nanako",
        "entries": [
            {
                "name": "Kansai International Airport",
                "time": "10:30-12:00",
                "category": "Arrival",
                "region": "Osaka",
                "description": "Touch down, breeze through Smart Immigration, and pick up ICOCA & "
                "Haruka passes for the fortnight of Kansai adventures.",
                "logistics": "Follow signage to JR Ticket Office (Level 2) for the ICOCA & HARUKA "
                "bundle; allow 45 minutes for immigration & luggage.",
                "booking": "Pre-fill Visit Japan Web QR codes; seat reservations optional on Haruka "
                "Express (green car recommended with luggage).",
                "companions": "You (landing solo)",
                "google_query": "Kansai International Airport Terminal 1",
                "budget_jpy": 0,
                "notes": "Meet Nana after she clocks off; keep evening gentle.",
            },
            {
                "name": "Hotel Agora Osaka Moriguchi",
                "time": "13:30-14:15",
                "category": "Lodging",
                "region": "Osaka (Keihan Line)",
                "description": "Check into a sleek Keihan-line base so Nana can commute easily on "
                "work days while you explore nearby neighbourhood cafés.",
                "logistics": "Haruka to Tennoji (45 min) → Osaka Loop to Kyobashi → Keihan express "
                "to Moriguchishi (total ~75 min). Request corner room with river view.",
                "booking": "Reserve flexible twin (Nov 14–18, 20–22, 25–26) on official site with "
                "breakfast add-on; note late check-in if flights delay.",
                "companions": "You + Nana",
                "google_query": "Hotel Agora Osaka Moriguchi",
                "budget_jpy": 24000,
                "notes": "Drop bags, shower, and short nap before meeting Nana.",
            },
            {
                "name": "Torisei Hirakata sake dinner",
                "time": "19:00-21:00",
                "category": "Food",
                "region": "Hirakata",
                "description": "Unwind with yakitori, warming nabe, and sake flights in Nana’s "
                "neighbourhood.",
                "logistics": "Keihan express from Moriguchishi to Hirakatashi after Nana finishes "
                "work; book corner booth for two.",
                "booking": "Reserve 19:00 counter seats via Tabelog; request gentle pace service "
                "for jet-lag.",
                "companions": "You + Nana",
                "google_query": "Torisei Hirakata",
                "budget_jpy": 7000,
                "notes": "Toast to the trip with light sake; stroll home via Hirakata river if "
                "energy allows.",
            },
        ],
    },
    {
        "date": "2025-11-15",
        "weekday": "Saturday",
        "title": "Osaka Minami street fashion & neon bites",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "Dive into Shinsaibashi, Amerikamura, and Dōtonbori with market grazing, kawaii "
        "stops, and night illuminations.",
        "nanako_work": False,
        "friends": "You + Nana",
        "entries": [
            {
                "name": "Brooklyn Roasting Company Kitahama",
                "time": "09:00-09:45",
                "category": "Coffee",
                "region": "Osaka",
                "description": "Fuel up riverside with Kyoto-sourced beans and plan the day over "
                "almond croissants in the airy loft.",
                "logistics": "Keihan express to Kitahama (20 min). Grab window seats upstairs for "
                "canal views.",
                "booking": "None; arrive before 09:30 to beat the weekend crowd.",
                "companions": "You + Nana",
                "google_query": "Brooklyn Roasting Company Kitahama",
                "budget_jpy": 1800,
                "notes": "Plot vintage stops; share almond croissant.",
            },
            {
                "name": "Shinsaibashi-suji & Amerikamura treasure hunt",
                "time": "10:00-12:30",
                "category": "Shopping",
                "region": "Osaka",
                "description": "Blend Shinsaibashi flagship finds with Amerikamura thrift gems—hunt "
                "vintage Harajuku vibes, refill skincare at @cosme, and hit Kinji "
                "for statement pieces.",
                "logistics": "Walk from Kitahama via Midosuji (15 min). Use lockers at Shinsaibashi "
                "Station to store purchases before lunch.",
                "booking": "None; map favourite boutiques in advance on shared Google Map.",
                "companions": "You + Nana",
                "google_query": "Shinsaibashi-suji Shopping Street",
                "budget_jpy": 15000,
                "notes": "Add Soosh + WEGO + Kinji to shared map.",
            },
            {
                "name": "Donguri Republic Shinsaibashi Ghibli store",
                "time": "12:30-13:00",
                "category": "Shopping",
                "region": "Osaka Minami",
                "description": "Pop into the Ghibli flagship for Totoro-themed homeware and party "
                "décor inspiration.",
                "logistics": "Inside Shinsaibashi PARCO B1; use Tax-Free counter for larger buys.",
                "booking": "None; queue may form for photo spots.",
                "companions": "You + Nana",
                "google_query": "Donguri Republic Shinsaibashi",
                "budget_jpy": 8000,
                "notes": "Pick up soot sprite lanterns for birthday suite styling.",
            },
            {
                "name": "Kuromon Ichiba Market tasting lunch",
                "time": "13:15-14:30",
                "category": "Food",
                "region": "Osaka",
                "description": "Grazing lunch of toro nigiri, charcoal-grilled scallops, and "
                "strawberry daifuku while chatting with fishmongers.",
                "logistics": "5-minute walk to Kuromon. Bring cash for stall snacks; aim for 6-8 "
                "bites (~¥3,000 pp).",
                "booking": "Optional: pre-book Kuromon tasting tour for insider stalls.",
                "companions": "You + Nana",
                "google_query": "Kuromon Ichiba Market",
                "budget_jpy": 6000,
                "notes": "Pick up fruit gift for Nana’s parents.",
            },
            {
                "name": "Namba Yasaka Shrine guardian photos",
                "time": "14:45-15:15",
                "category": "Culture",
                "region": "Osaka",
                "description": "Snap surreal shots in front of the iconic lion-head stage and leave "
                "ema wishes for the journey.",
                "logistics": "10-minute stroll from Kuromon via backstreets; best lighting "
                "mid-afternoon.",
                "booking": "None.",
                "companions": "You + Nana",
                "google_query": "Namba Yasaka Shrine",
                "budget_jpy": 500,
                "notes": "Collect goshuin stamp for the travel shrine book.",
            },
            {
                "name": "Dōtonbori promenade",
                "time": "15:30-16:30",
                "category": "Neighbourhood Stroll",
                "region": "Osaka",
                "description": "Ease into the neon with a golden-hour stroll beneath the Glico "
                "sign, sampling street snacks and capturing the first couple snaps.",
                "logistics": "Keihan line to Yodoyabashi → Midosuji subway to Namba (30 min). Hit "
                "Don Quijote for Suica/ICOCA top-ups and trip mascot souvenirs.",
                "booking": "None; aim for 17:00 for dusk reflections.",
                "companions": "You + Nana",
                "google_query": "Dotonbori",
                "budget_jpy": 2000,
                "notes": "Grab taiyaki and take midday photo set.",
            },
            {
                "name": "Tonbori River Cruise",
                "time": "17:00-17:30",
                "category": "Experience",
                "region": "Osaka",
                "description": "Sail past Osaka’s LED canyon; perfect for first-night wow shots and "
                "a quick rest for jet-lagged feet.",
                "logistics": "Board at Tazaemon-bashi Dock. Arrive 15 minutes early to swap QR "
                "voucher for tickets.",
                "booking": "Reserve online (¥1,200 pp); choose front-row seats for unobstructed "
                "photos.",
                "companions": "You + Nana",
                "google_query": "Tombori River Cruise",
                "budget_jpy": 2400,
                "notes": "Opt for sunset golden light.",
            },
            {
                "name": "Mizuno Okonomiyaki",
                "time": "18:00-19:15",
                "category": "Food",
                "region": "Osaka",
                "description": "Celebrate night one with caramelised okonomiyaki on a teppan "
                "counter, pairing yuzu highballs with the flagship yam batter.",
                "logistics": "Queue likely ~30 minutes; add name at 18:30 then explore Hozenji "
                "Yokocho until called. Order “Yamaimo-yaki” and seasonal special.",
                "booking": "No reservations; cash-focused (¥2,500 pp).",
                "companions": "You + Nana",
                "google_query": "Mizuno",
                "budget_jpy": 5000,
                "notes": "Request English menu for limited-time toppings.",
            },
            {
                "name": "Hozenji Yokocho lantern walk",
                "time": "19:30-20:00",
                "category": "Night Stroll",
                "region": "Osaka",
                "description": "Wind down along the mossy alley, wash the Fudō-myōō statue for "
                "blessings, and grab warabi-mochi to-go for the train ride home.",
                "logistics": "2-minute walk from Mizuno. Keihan trains run until after midnight "
                "back to Moriguchishi (last rapid ~23:50).",
                "booking": "None.",
                "companions": "You + Nana",
                "google_query": "Hozenji Yokocho",
                "budget_jpy": 1200,
                "notes": "Collect omamori for safe travels + relationship luck.",
            },
            {
                "name": "teamLab Botanical Garden Osaka",
                "time": "21:00-22:30",
                "category": "Immersive Art",
                "region": "Osaka",
                "description": "Nighttime digital art woven through Nagai Botanical Garden—glowing "
                "eggs, mirrored ponds, and luminous bamboo groves.",
                "logistics": "Subway Midosuji Line to Nagai (20 min from Shinsaibashi). Allow 90 "
                "minutes to wander loops; bring lightweight tripod alternative.",
                "booking": "Secure 18:00 entry slot (¥1,800 pp) through teamLab website two months "
                "ahead.",
                "companions": "You + Nana",
                "google_query": "teamLab Botanical Garden Osaka",
                "budget_jpy": 3600,
                "notes": "Late slot keeps night flexible; pack tripod alternative.",
            },
        ],
    },
    {
        "date": "2025-11-16",
        "weekday": "Sunday",
        "title": "Osaka Castle glow & Umeda skyline",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "Blend castle park moments with Umeda concept stores, rooftop views, and slow coffee.",
        "nanako_work": False,
        "friends": "You + Nana (invite Phil if in town)",
        "entries": [
            {
                "name": "Osaka Castle Park sunrise stroll",
                "time": "07:30-09:00",
                "category": "Culture",
                "region": "Osaka Castle",
                "description": "Catch morning light over Nishinomaru Garden, then head up the keep "
                "for historical exhibits.",
                "logistics": "Keihan line to Temmabashi, walk 10 minutes via OAP. Arrive before "
                "tour buses.",
                "booking": "Reserve skip-the-line tickets via Klook to avoid queues.",
                "companions": "You + Nana",
                "google_query": "Osaka Castle Museum",
                "budget_jpy": 1600,
                "notes": "Collect commemorative goshuin; scout photo spots for Nicole & Ken later.",
            },
            {
                "name": "Sakaisuji Honmachi brunch at & COFFEE MAISON",
                "time": "09:30-10:30",
                "category": "Food",
                "region": "Osaka Kita",
                "description": "Refuel with soufflé pancakes and seasonal fruit sodas before "
                "heading north.",
                "logistics": "Walk 12 minutes from Osaka Castle Park; arrive when doors open to "
                "skip queues.",
                "booking": "Book online waiting list if visiting peak Sunday.",
                "companions": "You + Nana",
                "google_query": "& COFFEE MAISON KITSUNE Osaka",
                "budget_jpy": 3000,
                "notes": "Order matcha latte for Nana; grab pastry for later shinkansen snacks.",
            },
            {
                "name": "Osaka Museum of Housing and Living",
                "time": "11:00-12:30",
                "category": "Culture",
                "region": "Osaka",
                "description": "Wander Edo-period Osaka streets recreated indoors—rent yukata for "
                "photos and learn urban history.",
                "logistics": "Subway to Tenjinbashisuji 6-chome; lockers available for bags. Entry "
                "¥600.",
                "booking": "Reserve time slot online (English site) to skip queue.",
                "companions": "You + Nana",
                "google_query": "Osaka Museum of Housing and Living",
                "budget_jpy": 2000,
                "notes": "Rent kimono briefly for castle-to-city contrast photos.",
            },
            {
                "name": "Takamura Wine & Coffee cupping flight",
                "time": "12:45-14:00",
                "category": "Food",
                "region": "Osaka",
                "description": "Celebrate the journey with artisanal coffee cupping and light "
                "brunch in a lofted roastery.",
                "logistics": "Taxi from W Osaka (10 min). Reserve tasting flight with seasonal "
                "beans.",
                "booking": "Book cupping session for two; pick up beans for home brewing.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Takamura Wine & Coffee Roasters",
                "budget_jpy": 8000,
                "notes": "Book cupping flight; pick up natural wine gift.",
            },
            {
                "name": "Grand Front Osaka depachika safari",
                "time": "14:15-15:30",
                "category": "Shopping",
                "region": "Umeda",
                "description": "Sample patisserie, sake, and wagashi in Umekita Cellar while "
                "curating birthday dessert table.",
                "logistics": "Walk from Takamura via Umeda Sky walkway; use lockers for purchases.",
                "booking": "None; consider Takashimaya card for discounts.",
                "companions": "You + Nana",
                "google_query": "Grand Front Osaka Umekita Cellar",
                "budget_jpy": 6000,
                "notes": "Grab PABLO mini cheesecakes for hotel snack stash.",
            },
            {
                "name": "HEP FIVE Ferris Wheel sky spin",
                "time": "16:00-16:45",
                "category": "Attractions",
                "region": "Umeda",
                "description": "Enjoy crimson gondola views sweeping over Osaka before dusk.",
                "logistics": "Ride from HEP FIVE 7F; use Amazing Pass if purchased.",
                "booking": "No booking; aim pre-sunset for short queue.",
                "companions": "You + Nana",
                "google_query": "HEP FIVE Ferris Wheel",
                "budget_jpy": 1000,
                "notes": "Snap timelapse for Japlan vlog intro.",
            },
            {
                "name": "Umeda Sky Building sunset cocktails",
                "time": "17:15-19:00",
                "category": "Viewpoint",
                "region": "Osaka",
                "description": "Toast with sky-high cocktails as Osaka transitions from gold to "
                "neon at the Floating Garden Observatory.",
                "logistics": "JR Loop to Osaka Station; elevator + escalator to 39F. Entry ¥1,500 "
                "pp; bar menu extra.",
                "booking": "Pre-book sunset slot; bring smartphone gimbal for skyline shots.",
                "companions": "You + Nana",
                "google_query": "Umeda Sky Building",
                "budget_jpy": 6000,
                "notes": "Invite Osaka-based friends for golden hour cheers.",
            },
            {
                "name": "Nakazakicho twilight ramen at Human Beings Everybody Noodles",
                "time": "19:15-20:30",
                "category": "Food",
                "region": "Osaka Kita",
                "description": "Slurp creative ramen bowls in the indie Nakazakicho district after "
                "skyline views.",
                "logistics": "8-minute walk from Umeda Sky; tiny shop so queue expected ~20 "
                "minutes.",
                "booking": "No reservations; add name to list and explore vintage shops while "
                "waiting.",
                "companions": "You + Nana",
                "google_query": "Human Beings Everybody Noodles",
                "budget_jpy": 2500,
                "notes": "Order yuzu shio ramen for lighter finish before Monday adventure.",
            },
        ],
    },
    {
        "date": "2025-11-17",
        "weekday": "Monday",
        "title": "Kyoto riverside & shrine symphony",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "Arashiyama dawn, Fushimi vermilion tunnels, and Uji tea rituals keep Kyoto magical "
        "yet efficient.",
        "nanako_work": False,
        "friends": "You + Nana",
        "entries": [
            {
                "name": "Arashiyama Bamboo Grove",
                "time": "06:30-07:30",
                "category": "Nature",
                "region": "Kyoto",
                "description": "Catch the bamboo groves before crowds arrive, capturing misty light "
                "beams and atmospheric morning sounds.",
                "logistics": "Keihan to Demachiyanagi → Hankyu to Arashiyama (~60 min). Ride first "
                "Hankyu departure 05:30 to arrive pre-dawn.",
                "booking": "None; pack tripod and optional kimono rental from 8:00 onwards.",
                "companions": "You + Nana",
                "google_query": "Arashiyama Bamboo Grove",
                "budget_jpy": 0,
                "notes": "Consider hiring local photographer for 07:00 mini-shoot.",
            },
            {
                "name": "Tenryu-ji Temple & Sogenchi Garden",
                "time": "07:45-09:00",
                "category": "Culture",
                "region": "Kyoto",
                "description": "Explore UNESCO Zen gardens glowing with momiji, and sip matcha "
                "overlooking the koi pond.",
                "logistics": "Entrance ¥500 + ¥300 for garden. Use north gate to exit directly into "
                "bamboo grove.",
                "booking": "Reserve shojin-ryori breakfast at Shigetsu for 8:00 seating if desired.",
                "companions": "You + Nana",
                "google_query": "Tenryu-ji Temple",
                "budget_jpy": 1600,
                "notes": "Check foliage reports for peak colour adjustments.",
            },
            {
                "name": "Riverside soba at Arashiyama Yoshimura",
                "time": "10:45-11:45",
                "category": "Food",
                "region": "Kyoto",
                "description": "Warm up with handmade soba and tempura while overlooking Togetsukyo "
                "Bridge from tatami seating.",
                "logistics": "Add name to queue by 10:30; ask for second-floor window seat. Average "
                "spend ¥2,000 pp.",
                "booking": "No reservations; request English menu for seasonal soba.",
                "companions": "You + Nana",
                "google_query": "Arashiyama Yoshimura",
                "budget_jpy": 4000,
                "notes": "Order yuba sashimi sampler to share.",
            },
            {
                "name": "Kimono Forest at Randen Arashiyama",
                "time": "12:00-12:20",
                "category": "Photo Spot",
                "region": "Kyoto",
                "description": "Wander through 600 illuminated kimono poles—perfect midday photo op "
                "before heading south.",
                "logistics": "Free entry beside Randen tram station. Capture boomerang videos under "
                "the sky projection well.",
                "booking": "None.",
                "companions": "You + Nana",
                "google_query": "Kimono Forest",
                "budget_jpy": 0,
                "notes": "Pick favourite pattern for future custom yukata order.",
            },
            {
                "name": "Fushimi Inari Taisha golden hour climb",
                "time": "14:30-16:30",
                "category": "Culture",
                "region": "Kyoto",
                "description": "Trace thousands of vermilion torii, pausing at Yotsutsuji for Kyoto "
                "panorama as lanterns begin to glow.",
                "logistics": "JR Nara Line to Inari (30 min). Climb to summit (~90 min round trip) "
                "with kitsune snack stops.",
                "booking": "None; consider renting kimono early morning for evening return photos.",
                "companions": "You + Nana",
                "google_query": "Fushimi Inari Taisha",
                "budget_jpy": 0,
                "notes": "Shift to mid-afternoon for softer light; climb to Yotsutsuji then descend "
                "for tea.",
            },
            {
                "name": "Gekkeikan Okura Sake Museum tasting flight",
                "time": "16:45-17:45",
                "category": "Food & Drink",
                "region": "Kyoto",
                "description": "Sample aged sake in the heart of Fushimi, blending history with "
                "guided tasting notes perfect for gifting.",
                "logistics": "Walk 12 minutes from Inari to Chushojima area (or quick Keihan ride). "
                "Last tasting entry 19:00.",
                "booking": "Reserve premium tasting course (¥1,000) for English guide availability.",
                "companions": "You + Nana",
                "google_query": "Gekkeikan Okura Sake Museum",
                "budget_jpy": 2000,
                "notes": "Ship bottle set to Nana’s apartment to avoid luggage weight.",
            },
            {
                "name": "Tsuen Tea master tasting",
                "time": "18:00-19:00",
                "category": "Food & Drink",
                "region": "Uji",
                "description": "Sip hand-whisked matcha and gyokuro flight at the world’s oldest "
                "tea shop, learning whisk techniques from tea masters.",
                "logistics": "Located beside Uji Bridge; reserve tea experience (¥2,500 pp). Allow "
                "extra time to browse teaware.",
                "booking": "Book tasting counter 2 weeks ahead; request English notes.",
                "companions": "You + Nana",
                "google_query": "Tsuen Tea",
                "budget_jpy": 5000,
                "notes": "Buy travel-friendly canisters for Tokyo friend gifts.",
            },
            {
                "name": "Kyoto Yakiniku Hiro (Shijo Kiyamachi)",
                "time": "19:30-21:00",
                "category": "Food",
                "region": "Kyoto",
                "description": "Indulge in wagyu lunch set with river views before heading back to "
                "Osaka.",
                "logistics": "Reserve tatami booth; lunch set ~¥3,500 pp. Use luggage storage at "
                "ryokan until departure.",
                "booking": "Book via TableCheck; note allergy preferences.",
                "companions": "You + Nana",
                "google_query": "Kyoto Yakiniku Hiro Shijo Kiyamachi",
                "budget_jpy": 7000,
                "notes": "Split premium platter to sample A5 cuts.",
            },
        ],
    },
    {
        "date": "2025-11-18",
        "weekday": "Tuesday",
        "title": "Hirakata co-work rhythm & cosy comforts",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "Keep pace with Nanako’s workday while layering in gentle treats and local "
        "relaxation.",
        "nanako_work": True,
        "friends": "You + Nana (workday)",
        "entries": [
            {
                "name": "Hirakata T-SITE coworking lounge",
                "time": "08:30-12:30",
                "category": "Work Base",
                "region": "Hirakata",
                "description": "Settle into T-SITE’s airy 4F coworking zone with killer library "
                "aesthetics while Nana logs into the office nearby.",
                "logistics": "5-minute walk from Hirakatashi Station. Day pass ¥1,650 with "
                "unlimited drip coffee.",
                "booking": "Reserve desk via Kansai Cowork app; request window seats.",
                "companions": "You + Nana (working)",
                "google_query": "Hirakata T-SITE",
                "budget_jpy": 1650,
                "notes": "Print Disney/USJ booking confirmations using onsite printers.",
            },
            {
                "name": "Café & Meal MUJI Hirakata T-SITE",
                "time": "12:30-13:15",
                "category": "Food",
                "region": "Hirakata",
                "description": "Healthy tray lunch of seasonal deli picks, miso soup, and yuzu soda "
                "to keep energy up mid-workday.",
                "logistics": "Order 4-item plate (~¥1,100). Grab take-home snacks for train rides "
                "later in the week.",
                "booking": "No reservations; self-service ordering kiosk.",
                "companions": "You + Nana",
                "google_query": "Café & Meal MUJI Hirakata T-SITE",
                "budget_jpy": 2200,
                "notes": "Check MUJI travel section for packing cubes before Tokyo.",
            },
            {
                "name": "Bear Paw Cafe mindful coffee break",
                "time": "15:30-16:00",
                "category": "Food",
                "region": "Hirakata",
                "description": "Swing by the kindness-powered Bear Paw Café for latte art and "
                "relaxing vibes.",
                "logistics": "10-minute walk from T-SITE; carry cashless payment.",
                "booking": "None; limited seating—consider take-out to T-SITE terrace.",
                "companions": "You + Nana",
                "google_query": "Bear Paw Cafe Hirakata",
                "budget_jpy": 1800,
                "notes": "Pick up postcard for Nicole and Ken’s arrival in Tokyo.",
            },
            {
                "name": "Gokurakuyu Hirakata evening soak",
                "time": "18:30-20:00",
                "category": "Wellness",
                "region": "Hirakata",
                "description": "Reward the workday with rotenburo and carbonated baths at the local "
                "sentō/spa complex.",
                "logistics": "Short taxi from station (~¥700). Bring onsen kit; tattoos require "
                "cover stickers (available at front desk).",
                "booking": "No booking needed; entry ¥850 + ¥220 towel rental.",
                "companions": "You + Nana",
                "google_query": "Gokurakuyu Hirakata",
                "budget_jpy": 2140,
                "notes": "Try the salt sauna and schedule shoulder massage (+¥2,000).",
            },
            {
                "name": "Kushikatsu Tanaka Hirakata",
                "time": "20:15-21:30",
                "category": "Food",
                "region": "Hirakata",
                "description": "Late-night skewers, DIY sauce, and highball towers steps from "
                "Nana’s station—casual, comforting, delicious.",
                "logistics": "Book corner booth; share kushi-katsu set + cheese fondue skewers. "
                "Average spend ¥3,000 for two with drinks.",
                "booking": "Use Tabelog to secure 20:15 slot (English-friendly).",
                "companions": "You + Nana",
                "google_query": "Kushikatsu Tanaka Hirakata",
                "budget_jpy": 6000,
                "notes": "Ask staff about November limited-time skewers for birthday week "
                "inspiration.",
            },
            {
                "name": "Kuzuha Mall late-night prep run",
                "time": "21:30-22:15",
                "category": "Shopping",
                "region": "Hirakata",
                "description": "Final stop for Heattech, birthday décor, and Shinkansen snacks.",
                "logistics": "Keihan line 3 minutes from Hirakatashi. Visit Loft + Kaldi Coffee "
                "Farm for treats.",
                "booking": "None.",
                "companions": "You + Nana",
                "google_query": "Kuzuha Mall",
                "budget_jpy": 12000,
                "notes": "Print Tokyo itinerary at Aeon copy station if needed.",
            },
        ],
    },
    {
        "date": "2025-11-19",
        "weekday": "Wednesday",
        "title": "Mount Koya retreat & temple night",
        "lodging": "Eko-in Temple (shukubo)",
        "summary": "Ride the scenic cable car, explore Okunoin, and sleep in tatami serenity with shojin "
        "cuisine.",
        "nanako_work": False,
        "friends": "You + Nana",
        "entries": [
            {
                "name": "Namba to Koyasan scenic ascent",
                "time": "09:00-11:30",
                "category": "Transit",
                "region": "Koyasan",
                "description": "Take the Nankai Limited Express to Gokurakubashi then cable car "
                "into the sacred mountain.",
                "logistics": "Reserve seats on Koya Limited Express; purchase Koyasan-World "
                "Heritage Ticket for discounts.",
                "booking": "Book train seats via Nankai app 30 days ahead.",
                "companions": "You + Nana",
                "google_query": "Nankai Koyasan Cable Car",
                "budget_jpy": 7000,
                "notes": "Pack overnight bag only; send main luggage back to Agora via Yamato.",
            },
            {
                "name": "Kongobu-ji painted screen walk",
                "time": "12:30-13:30",
                "category": "Culture",
                "region": "Koyasan",
                "description": "Admire fusuma paintings and Banryutei rock garden at the head "
                "temple of Shingon Buddhism.",
                "logistics": "5-minute taxi from Koyasan Station; shoe lockers available.",
                "booking": "No reservations; entry ¥1,000 payable in cash.",
                "companions": "You + Nana",
                "google_query": "Kongobuji Temple",
                "budget_jpy": 2000,
                "notes": "Attend tea service if offered; mindful photography only.",
            },
            {
                "name": "Eko-in Temple check-in & shojin dinner",
                "time": "15:30-19:30",
                "category": "Lodging",
                "region": "Koyasan",
                "description": "Settle into tatami room, join evening meditation, and savour "
                "plant-based kaiseki dinner.",
                "logistics": "Arrive by 15:00 for orientation; onsens available before dinner.",
                "booking": "Reserve Eko-in room with private bathroom via official site.",
                "companions": "You + Nana",
                "google_query": "Eko-in Temple",
                "budget_jpy": 42000,
                "notes": "Note curfew at 21:00; prepare gratitude journal entry before lights out.",
            },
            {
                "name": "Okunoin lantern night walk",
                "time": "20:00-21:30",
                "category": "Experience",
                "region": "Koyasan",
                "description": "Join guided torchlit stroll through Okunoin cemetery to Torodo Hall "
                "under 10,000 lanterns.",
                "logistics": "Meet at Eko-in lobby; wear warm layers and comfortable shoes.",
                "booking": "Book English night tour via temple concierge.",
                "companions": "You + Nana",
                "google_query": "Okunoin Cemetery",
                "budget_jpy": 6000,
                "notes": "Observe silence at Kobo Daishi mausoleum; no flash photography.",
            },
        ],
    },
    {
        "date": "2025-11-20",
        "weekday": "Thursday",
        "title": "Return to Osaka & bayfront sparkle",
        "lodging": "OMO7 Osaka by Hoshino Resorts",
        "summary": "Start with goma fire prayer, then head back for Osaka Bay date night ahead of Tokyo "
        "travels.",
        "nanako_work": False,
        "friends": "You + Nana",
        "entries": [
            {
                "name": "Eko-in morning meditation & goma fire",
                "time": "06:00-07:30",
                "category": "Wellness",
                "region": "Koyasan",
                "description": "Participate in morning sutra chanting followed by goma fire ritual "
                "for safe travels.",
                "logistics": "Arrive at main hall 10 minutes early; sit seiza or use stools "
                "provided.",
                "booking": "Included with stay—confirm attendance night prior.",
                "companions": "You + Nana",
                "google_query": "Eko-in Temple morning service",
                "budget_jpy": 0,
                "notes": "Write prayer tablets for upcoming Tokyo meet-ups.",
            },
            {
                "name": "OMO7 Osaka by Hoshino Resorts check-in",
                "time": "13:30-14:00",
                "category": "Lodging",
                "region": "Osaka",
                "description": "Shift to a design-forward stay with tatami lounges, onsen-style "
                "baths, and Osaka-focused concierge tours.",
                "logistics": "JR Kyoto Line to Tennoji (~45 min). Request skyline view room; enjoy "
                "welcome sweets.",
                "booking": "Stay Nov 20 only; add breakfast buffet and sauna package.",
                "companions": "You + Nana",
                "google_query": "OMO7 Osaka by Hoshino Resorts",
                "budget_jpy": 32000,
                "notes": "Drop luggage, enjoy sauna & lounge before bay outing.",
            },
            {
                "name": "Osaka Aquarium Kaiyukan twilight wander",
                "time": "16:00-18:30",
                "category": "Attractions",
                "region": "Osaka Bay",
                "description": "Marvel at whale sharks, jellyfish galaxy, and penguin habitats "
                "during evening lights.",
                "logistics": "JR Loop to Bentencho → Chuo Line to Osakako; store bags in lockers.",
                "booking": "Pre-book 16:00 timed tickets online to avoid queues.",
                "companions": "You + Nana",
                "google_query": "Osaka Aquarium Kaiyukan",
                "budget_jpy": 5400,
                "notes": "Check feeding schedule; capture manta rays on slow-mo.",
            },
            {
                "name": "Tempozan Marketplace seaside dinner",
                "time": "18:45-20:00",
                "category": "Food",
                "region": "Osaka Bay",
                "description": "Share kushikatsu, takoyaki, and dessert crepes beside the harbour "
                "lights.",
                "logistics": "Walk 3 minutes from Kaiyukan; browse souvenir shops for nautical "
                "gifts.",
                "booking": "No booking; use Gurunavi coupons for dining deals.",
                "companions": "You + Nana",
                "google_query": "Tempozan Marketplace",
                "budget_jpy": 4000,
                "notes": "Pick up Osaka Bay-themed trinkets for Nicole & Ken arrival.",
            },
            {
                "name": "Hirakata Park retro amusements",
                "time": "20:45-22:00",
                "category": "Experience",
                "region": "Hirakata",
                "description": "Celebrate end of workweek with gentle coasters, Ferris wheel "
                "selfies, and warm crepes in the vintage amusement park.",
                "logistics": "Discount twilight tickets from 15:00 (~¥1,500). Keep ride choices "
                "mild ahead of shinkansen weekend.",
                "booking": "Check seasonal illumination schedule; pre-book if limited.",
                "companions": "You + Nana",
                "google_query": "Hirakata Park",
                "budget_jpy": 3000,
                "notes": "Ride Sky Walker night loop before packing for Tokyo.",
            },
        ],
    },
    {
        "date": "2025-11-21",
        "weekday": "Friday",
        "title": "Work sprint & shinkansen to Shibuya",
        "lodging": "sequence MIYASHITA PARK",
        "summary": "Log a focused work block, then glide to Tokyo to set up base and catch up with "
        "Nicole & Ken.",
        "nanako_work": True,
        "friends": "You + Nana (Nicole & Ken join evening)",
        "entries": [
            {
                "name": "Hirakata T-SITE cowork reset",
                "time": "08:00-11:00",
                "category": "Work Base",
                "region": "Hirakata",
                "description": "Return to favourite desks for focus time, finalise Tokyo to-do "
                "lists, and sync with friends online.",
                "logistics": "Grab corner booths with power outlets; schedule midday break at "
                "11:30.",
                "booking": "Reuse multi-day pass for coworking discount.",
                "companions": "You + Nana",
                "google_query": "Hirakata T-SITE",
                "budget_jpy": 1650,
                "notes": "Nanako logs into Friday stand-ups before departure.",
            },
            {
                "name": "Nozomi express northbound with ekiben",
                "time": "12:00-14:30",
                "category": "Transit",
                "region": "Shinkansen",
                "description": "Ride Nozomi 20 from Shin-Osaka to Shinagawa with seasonal ekiben "
                "lunch and trip journaling.",
                "logistics": "Reserve seats in car 12 for luggage; pick up ekiben at Shin-Osaka "
                "before boarding.",
                "booking": "Book via SmartEX; aim for 12:13 departure to arrive before check-in.",
                "companions": "You + Nana",
                "google_query": "Nozomi Shinkansen Shin-Osaka to Tokyo",
                "budget_jpy": 28000,
                "notes": "Share location with Nicole & Ken so they can meet at hotel lobby.",
            },
            {
                "name": "sequence MIYASHITA PARK check-in",
                "time": "14:45-15:15",
                "category": "Lodging",
                "region": "Tokyo",
                "description": "Drop bags at the design hotel hugging Miyashita Park—perfect base "
                "between Shibuya and Harajuku.",
                "logistics": "Nozomi 16 from Shin-Osaka (08:00-10:30). Early baggage drop "
                "available; request high-floor park view.",
                "booking": "Reserve 1 night (Nov 22) double room; ask for late checkout 12:00.",
                "companions": "You + Nana",
                "google_query": "sequence MIYASHITA PARK",
                "budget_jpy": 26000,
                "notes": "Request park-facing room; drop Nicole & Ken’s overnight bags.",
            },
            {
                "name": "Shibuya Crossing twilight photos",
                "time": "16:00-16:45",
                "category": "Attractions",
                "region": "Tokyo Shibuya",
                "description": "Capture multi-angle shots of the scramble from Magnet rooftop and "
                "street level.",
                "logistics": "Use Magnet by Shibuya109 rooftop (¥600); coordinate with Nicole & Ken "
                "for meet-up.",
                "booking": "No booking; arrive 10 minutes early for rooftop slots.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Shibuya Crossing",
                "budget_jpy": 1500,
                "notes": ".",
            },
            {
                "name": "Shibuya 109 trend scout",
                "time": "16:45-18:15",
                "category": "Shopping",
                "region": "Tokyo Shibuya",
                "description": "Browse Shibuya 109, uncover J-fashion collabs, and prep outfits for "
                "birthday party.",
                "logistics": "Store luggage in hotel; use tax-free counters with passport.",
                "booking": "None; plan wishlist via Shibuya 109 app.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Shibuya 109",
                "budget_jpy": 12000,
                "notes": "Pick up matching accessories and limited-edition Shin merch.",
            },
            {
                "name": "Kaikaya by the Sea izakaya dinner",
                "time": "19:00-21:00",
                "category": "Food",
                "region": "Tokyo Shibuya",
                "description": "Celebrate reunion with creative seafood izakaya plates and sake "
                "flights.",
                "logistics": "10-minute walk from hotel; bring cash for small dishes.",
                "booking": "Reserve tatami room for four; note shellfish allergies.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Kaikaya by the Sea",
                "budget_jpy": 20000,
                "notes": "Surprise Ken with mini dessert for his upcoming birthday.",
            },
        ],
    },
    {
        "date": "2025-11-22",
        "weekday": "Saturday",
        "title": "Tokyo DisneySea sparkle with the crew",
        "lodging": "MIMARU Tokyo Shinjuku WEST",
        "summary": "Spend the day at DisneySea with holiday overlays, lounge recharge, and cosy Shinjuku "
        "sleepover.",
        "nanako_work": False,
        "friends": "You + Nana + Nicole + Ken",
        "entries": [
            {
                "name": "Tokyo DisneySea adventure",
                "time": "08:00-19:30",
                "category": "Theme Park",
                "region": "Tokyo",
                "description": "Soar on Soaring, dive into Journey to the Center, and catch the "
                "evening Harbor of Dreams show with Christmas overlays.",
                "logistics": "Resort line from Maihama Station; use Premier Access for Soaring + "
                "Journey to shorten queues.",
                "booking": "Buy 1-day passports (¥10,900 pp) + 2 Premier Access per headline "
                "attraction.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Tokyo DisneySea",
                "budget_jpy": 43600,
                "notes": "Coordinate Genie Premier Access windows; matching earth-tone outfits.",
            },
            {
                "name": "Disney Ambassador Hotel lounge reset",
                "time": "14:00-15:30",
                "category": "Lodging",
                "region": "Tokyo",
                "description": "Afternoon tea at Hyperion Lounge to recharge mid-park with seasonal "
                "desserts and photo ops.",
                "logistics": "5-minute walk from park entrance; deposit bags with bell desk before "
                "lounge visit.",
                "booking": "Reserve 14:00 seating via official app; note birthday celebration.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Disney Ambassador Hotel",
                "budget_jpy": 16000,
                "notes": "Collect exclusive hotel pin for keepsake board.",
            },
            {
                "name": "MIMARU Tokyo Shinjuku WEST pajama party",
                "time": "21:00-23:30",
                "category": "Lodging",
                "region": "Tokyo",
                "description": "Apartment-style suite with tatami bunk beds, kitchen for snacks, "
                "and board games for a nostalgic sleepover.",
                "logistics": "Taxi from Nihonbashi (~25 min). Request Pokémon-themed room if "
                "available.",
                "booking": "Book 2-bedroom suite for Nov 23; add breakfast basket.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "MIMARU Tokyo Shinjuku West",
                "budget_jpy": 36000,
                "notes": "Set up board games and projector for post-park wind-down.",
            },
        ],
    },
    {
        "date": "2025-11-23",
        "weekday": "Sunday",
        "title": "Toyosu mornings & Odaiba glow",
        "lodging": "MIMARU Tokyo Shinjuku WEST",
        "summary": "Balance art immersion with café cuteness before a karaoke nightcap.",
        "nanako_work": False,
        "friends": "You + Nana + Nicole + Ken",
        "entries": [
            {
                "name": "Toyosu Market sushi breakfast",
                "time": "07:30-09:00",
                "category": "Food",
                "region": "Tokyo Toyosu",
                "description": "Queue early for Daiwa Sushi omakase and check rooftop gardens "
                "overlooking the bay.",
                "logistics": "Yurikamome to Shijo-mae; arrive 07:00 to secure counter seats.",
                "booking": "Some stalls accept reservations—call ahead for group of four.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Toyosu Market Daiwa Sushi",
                "budget_jpy": 16000,
                "notes": "Grab souvenir knives for cooking friends.",
            },
            {
                "name": "teamLab Planets TOKYO DMM",
                "time": "09:30-11:30",
                "category": "Immersive Art",
                "region": "Tokyo",
                "description": "Barefoot, multi-sensory art spaces with mirrored water "
                "rooms—perfect for collaborative photos.",
                "logistics": "Yurikamome to Shin-Toyosu. Bring small towel for water installations.",
                "booking": "Book 09:00 slot (¥3,800 pp). Add photo plan for digital downloads.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "teamLab Planets TOKYO",
                "budget_jpy": 15200,
                "notes": "Coordinate matching monochrome outfits for reflective shots.",
            },
            {
                "name": "Pokémon Café Nihonbashi",
                "time": "12:30-14:00",
                "category": "Food",
                "region": "Tokyo",
                "description": "Adorable character plates, latte art, and special edition merch "
                "with tableside Pikachu show.",
                "logistics": "5F Takashimaya annex; arrive 15 minutes early to check in. Average "
                "spend ¥3,000 pp.",
                "booking": "Reservations open exactly 31 days in advance at 18:00 JST—set reminder.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Pokémon Café Nihonbashi",
                "budget_jpy": 12000,
                "notes": "Order seasonal dessert for Ken’s birthday shout-out.",
            },
            {
                "name": "Odaiba Seaside Park & Palette Town wheel",
                "time": "15:00-17:00",
                "category": "Attractions",
                "region": "Tokyo Odaiba",
                "description": "Stroll the waterfront, shop DiverCity, and ride the Daikanransha "
                "Ferris wheel at sunset.",
                "logistics": "Yurikamome line from Toyosu; lockers available at Aqua City.",
                "booking": "Reserve priority gondola for golden hour views.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Palette Town Ferris Wheel",
                "budget_jpy": 4000,
                "notes": "Swing by Unicorn Gundam for photo op.",
            },
            {
                "name": "Karaoke Kan Shibuya all-out session",
                "time": "20:00-22:30",
                "category": "Nightlife",
                "region": "Tokyo",
                "description": "Sing through anime themes, K-pop, and nostalgic hits with drink "
                "package and custom cake delivery.",
                "logistics": "Reserve party room with neon lighting; bring Polaroid for instant "
                "keepsakes.",
                "booking": "Book 3-hour plan with unlimited soft drinks + two cocktails per person.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Karaoke Kan Shibuya",
                "budget_jpy": 18000,
                "notes": "Bring Polaroid for souvenir wall; celebrate Shin & your birthdays.",
            },
        ],
    },
    {
        "date": "2025-11-24",
        "weekday": "Monday",
        "title": "Harajuku vibes & skyline toasts",
        "lodging": "sequence MIYASHITA PARK",
        "summary": "Harajuku fashion, shrine calm, and Shibuya nightlife with James and Phil joining.",
        "nanako_work": False,
        "friends": "You + Nana + Nicole + Ken + James (+ Phil evening)",
        "entries": [
            {
                "name": "Meiji Jingu morning blessing",
                "time": "09:00-10:00",
                "category": "Culture",
                "region": "Tokyo Harajuku",
                "description": "Walk the forested approach, offer ema, and pick omamori for "
                "friends.",
                "logistics": "Enter via Harajuku Station South Gate; cleanse at temizuya.",
                "booking": "No booking; avoid wedding procession lanes.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Meiji Jingu Shrine",
                "budget_jpy": 1000,
                "notes": "Write wish for Nanako’s work balance and shared adventures.",
            },
            {
                "name": "Afuri Harajuku yuzu ramen lunch",
                "time": "11:00-12:00",
                "category": "Food",
                "region": "Tokyo",
                "description": "Freshen up with light yuzu shio ramen and vegan seasonal bowls "
                "before diving into Takeshita chaos.",
                "logistics": "Order via vending machine; share karaage side. Seating limited—arrive "
                "before peak rush.",
                "booking": "No reservations; have Suica ready for quick payment.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Afuri Harajuku",
                "budget_jpy": 5000,
                "notes": "Nicole loves spicy—grab the tsukemen option for her.",
            },
            {
                "name": "Takeshita Street & Harajuku ateliers",
                "time": "12:00-14:30",
                "category": "Shopping",
                "region": "Tokyo",
                "description": "Hop between Laforet pop-ups, 6%DOKIDOKI, and vintage sneaker shops "
                "while trying crepes and purikura booths.",
                "logistics": "Create shared AirDrop album for haul photos. Visit Moshi Moshi Box "
                "for free Wi-Fi & maps.",
                "booking": "Book 15:00 purikura slot at NOA Café for group shots.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Takeshita Street",
                "budget_jpy": 20000,
                "notes": "Add Soosh + 6%DOKIDOKI + Kiddy Land map pins.",
            },
            {
                "name": "Cat Street design crawl",
                "time": "14:30-15:30",
                "category": "Shopping",
                "region": "Tokyo Harajuku",
                "description": "Stroll Cat Street boutiques for indie fashion, vintage denim, and "
                "café pop-ups.",
                "logistics": "Walk toward Omotesando; stop by Ragtag and vintage sneaker shops.",
                "booking": "None; plan 15:00 coffee stop at The Roastery by Nozy.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Cat Street Harajuku",
                "budget_jpy": 5000,
                "notes": "Scout gift for Bayliss at Japanese design stores.",
            },
            {
                "name": "Daikanyama T-Site slow brew",
                "time": "16:00-17:00",
                "category": "Food",
                "region": "Tokyo Daikanyama",
                "description": "Sip slow-drip coffee among Tsutaya’s curated stacks and vinyl "
                "corner.",
                "logistics": "Walk 10 minutes from Shibuya or ride Tokyu Toyoko line.",
                "booking": "No booking; reserve reading table via app if staying longer.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Daikanyama T-Site",
                "budget_jpy": 2500,
                "notes": "Pick up photobooks for Japlan scrapbooking.",
            },
            {
                "name": "Nakameguro twilight canal walk",
                "time": "17:15-18:00",
                "category": "Attractions",
                "region": "Tokyo Meguro",
                "description": "Wander along the Meguro River lights, stopping for gelato and "
                "boutique shopping.",
                "logistics": "Walk or train to Nakameguro Station; check Blue Bottle for limited "
                "roast.",
                "booking": "None; hold dinner reservations for later.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Nakameguro River Walk",
                "budget_jpy": 2000,
                "notes": "Scout interior shops for Nana’s apartment décor ideas.",
            },
            {
                "name": "Shibuya Sky golden hour meet-up",
                "time": "18:00-19:30",
                "category": "Viewpoint",
                "region": "Tokyo",
                "description": "Meet James for panoramic city views as the scramble lights up "
                "below—capture drone-like shots from the helipad deck.",
                "logistics": "Pre-book 17:00 entry (¥2,200). Lockers for bags; no tripods allowed "
                "but smartphone gimbals ok.",
                "booking": "Purchase tickets 2 months ahead; reserve Sky Gallery café seating.",
                "companions": "You + Nana + Nicole + Ken + James + Phil",
                "google_query": "SHIBUYA SKY",
                "budget_jpy": 11000,
                "notes": "Coordinate James + Phil arrival; book Sky Gallery table.",
            },
            {
                "name": "Gonpachi Shibuya dinner",
                "time": "19:45-21:45",
                "category": "Food",
                "region": "Tokyo",
                "description": "Izakaya feast with yakitori, sushi rolls, and sake flights inspired "
                "by Kill Bill vibes to cap the day.",
                "logistics": "10-minute walk from Shibuya Crossing. Order set menu (~¥5,000 pp) "
                "plus vegetarian sides for Ken.",
                "booking": "Reserve private tatami room for 6; mention birthdays for dessert "
                "sparklers.",
                "companions": "You + Nana + Nicole + Ken + James + Phil",
                "google_query": "Gonpachi Shibuya",
                "budget_jpy": 30000,
                "notes": "Pay via credit card; split bill later using shared tracker.",
            },
        ],
    },
    {
        "date": "2025-11-25",
        "weekday": "Tuesday",
        "title": "Asakusa sunrise & Osaka return reset",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "Start with Asakusa calm, let Nanako log on mid-morning, and glide back to Kansai for "
        "street eats.",
        "nanako_work": True,
        "friends": "You + Nana (friends depart to Chiba)",
        "entries": [
            {
                "name": "Senso-ji sunrise rituals",
                "time": "06:30-07:30",
                "category": "Culture",
                "region": "Tokyo Asakusa",
                "description": "Offer incense at Senso-ji before crowds, capture Nakamise empty, "
                "and draw omikuji.",
                "logistics": "Ginza Line first train from Shibuya; bring ¥100 coins.",
                "booking": "No booking; check sunrise time for lighting.",
                "companions": "You + Nana",
                "google_query": "Senso-ji",
                "budget_jpy": 500,
                "notes": "Grab ningyo-yaki to share on the shinkansen.",
            },
            {
                "name": "Tokyo Skytree Tembo Deck",
                "time": "08:00-09:30",
                "category": "Attractions",
                "region": "Tokyo Sumida",
                "description": "Take in panoramic views and plan future adventures from the 350m "
                "deck.",
                "logistics": "Walk or train to Oshiage; use Fast Skytree Ticket for shorter queue.",
                "booking": "Reserve 08:00 entry online; bring passport for discount.",
                "companions": "You + Nana",
                "google_query": "Tokyo Skytree",
                "budget_jpy": 6400,
                "notes": "Pick up Sumida Aquarium matcha sweets downstairs.",
            },
            {
                "name": "MIMARU remote work sprint",
                "time": "10:00-12:00",
                "category": "Work",
                "region": "Tokyo Shinjuku",
                "description": "Nanako logs into Tuesday meetings while you pack and coordinate "
                "Osaka evening.",
                "logistics": "Use MIMARU co-working nook; ensure stable Wi-Fi before calls.",
                "booking": "Included with stay; check out extended to 12:00.",
                "companions": "You + Nana",
                "google_query": "MIMARU Tokyo Shinjuku WEST",
                "budget_jpy": 0,
                "notes": "Ship Tokyo purchases via Yamato before departure.",
            },
            {
                "name": "Asakusaimahan Sukiyaki lunch",
                "time": "12:15-13:30",
                "category": "Food",
                "region": "Tokyo Asakusa",
                "description": "Indulge in wagyu sukiyaki as farewell treat before hopping south.",
                "logistics": "15-minute taxi from MIMARU; store luggage near table.",
                "booking": "Reserve private room; request medium-rare finish.",
                "companions": "You + Nana",
                "google_query": "Asakusa Imahan (Honten)",
                "budget_jpy": 14000,
                "notes": "Order extra raw egg for dipping; toast upcoming Osaka birthday week.",
            },
            {
                "name": "Tokyo Character Street souvenir dash",
                "time": "13:45-14:30",
                "category": "Shopping",
                "region": "Tokyo Station",
                "description": "Grab limited NHK and Ghibli merch along the station basement "
                "arcade.",
                "logistics": "Arrive 45 minutes before train; use coin lockers for luggage.",
                "booking": "None; check NHK character shop for Bayliss gift.",
                "companions": "You + Nana",
                "google_query": "Tokyo Character Street",
                "budget_jpy": 8000,
                "notes": "Pick up Doraemon sweets for Osaka friends.",
            },
            {
                "name": "Nozomi ride south with ekiben",
                "time": "15:00-17:30",
                "category": "Transit",
                "region": "Shinkansen",
                "description": "Return to Shin-Osaka with matcha sweets and digital journaling of "
                "Tokyo memories.",
                "logistics": "Board Nozomi 47; car 11 for quieter ride.",
                "booking": "Book via SmartEX; schedule arrival ~17:13 for Osaka evening.",
                "companions": "You + Nana",
                "google_query": "Nozomi Shinkansen Tokyo to Shin-Osaka",
                "budget_jpy": 28000,
                "notes": "Send Nicole & Ken off at Tokyo Station before boarding.",
            },
            {
                "name": "Torame Yokocho night market dinner",
                "time": "19:00-21:00",
                "category": "Food",
                "region": "Osaka",
                "description": "Graze across Osaka comfort classics—takoyaki, kushikatsu, craft "
                "beer—under a retro neon arcade.",
                "logistics": "Located in Namba. Reload ICOCA before arrival; mix-and-match small "
                "plates (~¥4,000 total).",
                "booking": "No bookings; arrive early to secure communal table.",
                "companions": "You + Nana",
                "google_query": "Torame Yokocho",
                "budget_jpy": 8000,
                "notes": "Scout dessert at adjoining “Electric Cafe” for matcha parfaits.",
            },
        ],
    },
    {
        "date": "2025-11-26",
        "weekday": "Wednesday",
        "title": "Creative Osaka reset & Kaiyukan night",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "Morning catch-up, Lucua treats, luminous art, and ramen comfort back in Minami.",
        "nanako_work": False,
        "friends": "You + Nana",
        "entries": [
            {
                "name": "Hirakata T-SITE cowork catch-up",
                "time": "09:00-11:00",
                "category": "Work Base",
                "region": "Hirakata",
                "description": "Dial back into work mode, archive Tokyo photos, and prep Osaka "
                "birthday logistics alongside Nana.",
                "logistics": "Book day desk again; bring souvenirs for Nana’s colleagues.",
                "booking": "Consider 5-day pass if returning later.",
                "companions": "You + Nana (working)",
                "google_query": "Hirakata T-SITE",
                "budget_jpy": 1650,
                "notes": "Upload Tokyo photos; organise birthday invites.",
            },
            {
                "name": "Osaka Station City rooftop lunch at Lucua Food Hall",
                "time": "12:00-13:15",
                "category": "Food",
                "region": "Osaka Kita",
                "description": "Graze through bento stands and craft coffee before an artful "
                "afternoon.",
                "logistics": "Take Keihan to Kitahama then walk; use rooftop seating for picnic "
                "vibe.",
                "booking": "None; consider Ekiben specialty for upcoming day trips.",
                "companions": "You + Nana",
                "google_query": "LUCUA Food Hall",
                "budget_jpy": 2500,
                "notes": "Check JR ticket office for Himeji reservations.",
            },
            {
                "name": "teamLab Botanical Garden Osaka (encore)",
                "time": "19:00-20:30",
                "category": "Art",
                "region": "Osaka",
                "description": "Return for alternate route through luminous installations with "
                "fresh perspectives.",
                "logistics": "Subway Midosuji to Nagai; bring tickets purchased earlier or rebook "
                "if needed.",
                "booking": "Book 19:00 slot to enjoy smaller crowds on weekday.",
                "companions": "You + Nana",
                "google_query": "teamLab Botanical Garden Osaka",
                "budget_jpy": 2000,
                "notes": "Focus on long-exposure photography practice.",
            },
            {
                "name": "Ichiran Ramen Dotonbori late-night bowls",
                "time": "21:00-22:00",
                "category": "Food",
                "region": "Osaka Minami",
                "description": "Wind down with customisable tonkotsu ramen in private booths.",
                "logistics": "Queue typically 15 minutes on weekdays; use ticket machine to order.",
                "booking": "No booking; bring cash/IC.",
                "companions": "You + Nana",
                "google_query": "Ichiran Dotonbori",
                "budget_jpy": 2000,
                "notes": "Experiment with spice level 6 for Nicole’s recommended heat.",
            },
        ],
    },
    {
        "date": "2025-11-27",
        "weekday": "Thursday",
        "title": "Himeji heritage & Kobe indulgence",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "White Heron castle climb, herb garden views, teppan lunch, onsen soak, and harbour "
        "sparkle.",
        "nanako_work": False,
        "friends": "You + Nana",
        "entries": [
            {
                "name": "Himeji Castle early climb",
                "time": "08:00-10:00",
                "category": "Culture",
                "region": "Himeji",
                "description": "Explore the White Heron Castle keep and Koko-en gardens before "
                "crowds.",
                "logistics": "JR Special Rapid from Osaka to Himeji (1 hr); arrive before gates "
                "open.",
                "booking": "Reserve e-tickets to skip queue; pick up audio guide.",
                "companions": "You + Nana",
                "google_query": "Himeji Castle",
                "budget_jpy": 2000,
                "notes": "Capture drone-style shots from observation deck (no actual drone).",
            },
            {
                "name": "Kobe Nunobiki Herb Gardens & Ropeway",
                "time": "11:00-13:00",
                "category": "Nature",
                "region": "Kobe",
                "description": "Glide up the ropeway for panoramic views and wander fragrant "
                "greenhouses with seasonal blooms.",
                "logistics": "JR rapid to Shin-Kobe (30 min). Ropeway combo ticket ¥1,800; arrive "
                "early for crowd-free photos.",
                "booking": "Purchase e-tickets online for express entry.",
                "companions": "You + Nana",
                "google_query": "Kobe Nunobiki Herb Gardens",
                "budget_jpy": 3600,
                "notes": "Try herb soft serve at summit café.",
            },
            {
                "name": "Steakland Kobe lunch set",
                "time": "13:15-14:30",
                "category": "Food",
                "region": "Kobe",
                "description": "Classic teppan Kobe beef lunch with live chef performance—best "
                "value wagyu feast.",
                "logistics": "10-minute walk from Sannomiya. Lunch set ¥3,480 pp includes soup, "
                "salad, rice, dessert.",
                "booking": "Call morning-of to secure counter seats; note medium-rare preference.",
                "companions": "You + Nana",
                "google_query": "Steakland Kobe",
                "budget_jpy": 8000,
                "notes": "Add garlic chips and sparkling sake pairing.",
            },
            {
                "name": "Arima Onsen Taiko-no-yu",
                "time": "15:30-18:00",
                "category": "Wellness",
                "region": "Arima",
                "description": "Soak in gold and silver springs, explore cave baths, and book a "
                "private relaxation room.",
                "logistics": "Hankyu Bus from Sannomiya (35 min). Entry ¥2,750; rent yukata + towel "
                "set.",
                "booking": "Reserve private tatami lounge for two hours (+¥3,000).",
                "companions": "You + Nana",
                "google_query": "Arima Onsen Taiko-no-yu",
                "budget_jpy": 8000,
                "notes": "Hydrate with locally bottled carbonated Arima water.",
            },
            {
                "name": "Kobe Harborland night stroll",
                "time": "19:00-20:30",
                "category": "Night Stroll",
                "region": "Kobe",
                "description": "Capture mosaic lights, ride the Ferris wheel if energy allows, and "
                "share harbourfront desserts.",
                "logistics": "JR to Kobe Station; 5-minute walk. Check Luminarie schedule for "
                "possible early displays.",
                "booking": "None.",
                "companions": "You + Nana",
                "google_query": "Kobe Harborland",
                "budget_jpy": 2000,
                "notes": "Try Godiva hot chocolate for warm hands.",
            },
        ],
    },
    {
        "date": "2025-11-28",
        "weekday": "Friday",
        "title": "Osaka birthday supernova",
        "lodging": "W Osaka (Marvelous Suite)",
        "summary": "Nanako logs off then the crew rallies for glam prep, teppanyaki, karaoke, and "
        "rooftop toasts.",
        "nanako_work": True,
        "friends": "You + Nana + Nicole + Ken + Osaka friends",
        "entries": [
            {
                "name": "W Osaka check-in & suite styling",
                "time": "13:00-14:00",
                "category": "Lodging",
                "region": "Osaka",
                "description": "Secure a Marvelous Suite for party-ready lighting, stash "
                "decorations, and arrange welcome amenities.",
                "logistics": "Check-in early via Marriott Bonvoy elite chat; request high-floor "
                "city view and extra vanity mirrors.",
                "booking": "Stay Nov 28-30; add birthday amenity + late checkout on 30 Nov.",
                "companions": "You (setup) + Nana after work + Nicole & Ken (guest access)",
                "google_query": "W Osaka",
                "budget_jpy": 95000,
                "notes": "Nanako logs off at noon; begin setup with Nicole & Ken assisting.",
            },
            {
                "name": "Afternoon glam & restock run",
                "time": "14:00-16:00",
                "category": "Prep",
                "region": "Osaka Shinsaibashi",
                "description": "Set up décor, finalise playlist, and grab last-minute sweets at "
                "Daimaru.",
                "logistics": "Divide tasks: Nana handles balloons, you prep tech, friends collect "
                "cake.",
                "booking": "Confirm cake delivery window at 15:00.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Daimaru Shinsaibashi",
                "budget_jpy": 10000,
                "notes": "Check sound system cables and Polaroid film before guests arrive.",
            },
            {
                "name": "MYDO Teppanyaki birthday dinner",
                "time": "18:30-20:30",
                "category": "Food",
                "region": "Osaka",
                "description": "Table-side wagyu, flambéed seafood, and custom dessert with dual "
                "birthday shout-outs for you and Ken.",
                "logistics": "Located inside W Osaka. Request private teppan counter with six "
                "seats.",
                "booking": "Pre-order cake + champagne tower; confirm shellfish allergies.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "MYDO Teppanyaki",
                "budget_jpy": 60000,
                "notes": "Play curated playlist through restaurant’s sound system (share via "
                "Spotify link).",
            },
            {
                "name": "Karaoke Kan Shinsaibashi takeover",
                "time": "21:00-23:30",
                "category": "Nightlife",
                "region": "Osaka",
                "description": "Private neon room with unlimited drinks, photobooth props, and "
                "birthday slideshow during choruses.",
                "logistics": "Reserve VIP room; bring HDMI cable for slideshow. Order sparkling "
                "sake tower.",
                "booking": "Book 3-hour premium plan with open bar via Jalan Net.",
                "companions": "You + Nana + Nicole + Ken + Osaka friends (optional)",
                "google_query": "Karaoke Kan Shinsaibashi 2-chome",
                "budget_jpy": 24000,
                "notes": "Surprise Ken with co-birthday montage at 22:00.",
            },
            {
                "name": "Bar Nayuta sky cocktails",
                "time": "23:45-01:00",
                "category": "Nightlife",
                "region": "Osaka",
                "description": "Wind down with rooftop mixology featuring yuzu gin fizzes and "
                "dessert cocktails overlooking Osaka Castle lights.",
                "logistics": "5-minute taxi from karaoke. Dress smart-casual; limited seating at "
                "counter.",
                "booking": "Reserve 23:45 slot; request custom drink named “Japlan Nova”.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Bar Nayuta",
                "budget_jpy": 16000,
                "notes": "Bring small thank-you gifts for bartenders (Aussie chocolate).",
            },
        ],
    },
    {
        "date": "2025-11-29",
        "weekday": "Saturday",
        "title": "Kyoto foliage encore with friends",
        "lodging": "Hotel Agora Osaka Moriguchi",
        "summary": "Spend a relaxed finale in Kyoto with foliage moments, tofu lunch, and illuminated "
        "zen paths.",
        "nanako_work": False,
        "friends": "You + Nana + Nicole + Ken",
        "entries": [
            {
                "name": "Eikan-dō Zenrin-ji morning glow",
                "time": "09:00-10:30",
                "category": "Culture",
                "region": "Kyoto",
                "description": "Marvel at fiery maple reflections in the Hojo Pond and climb the "
                "Tahoto pagoda for sweeping views.",
                "logistics": "Keihan from Yodoyabashi to Jingū-Marutamachi then taxi (15 min). "
                "Entry ¥1,000; illumination tickets separate.",
                "booking": "Buy advance tickets online to skip queue; bring printed QR codes.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Eikan-do Zenrin-ji",
                "budget_jpy": 4000,
                "notes": "Shoot birthday-week group photo on the Hojo Bridge.",
            },
            {
                "name": "Philosopher’s Path stroll",
                "time": "10:30-11:30",
                "category": "Nature",
                "region": "Kyoto",
                "description": "Leisurely walk along the canal beneath amber leaves, stopping for "
                "craft boutiques and gelato.",
                "logistics": "Start near Eikan-dō and head north; peek into artisanal shops like "
                "Ginkaku-ji Seseragi.",
                "booking": "None.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Philosopher’s Path",
                "budget_jpy": 2000,
                "notes": "Grab seasonal gelato at Sfera Bar Satén en route.",
            },
            {
                "name": "Okutan Nanzenji yudofu lunch",
                "time": "12:00-13:30",
                "category": "Food",
                "region": "Kyoto",
                "description": "Traditional tofu kaiseki in a tatami room overlooking a moss "
                "garden—warming and serene.",
                "logistics": "Reserve tatami room; lunch course ¥3,800 pp. Remove shoes at entry.",
                "booking": "Call ahead; mention vegetarian-friendly preferences.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Okutan Nanzenji",
                "budget_jpy": 16000,
                "notes": "Pre-order sansho pepper tofu for take-home treat.",
            },
            {
                "name": "Tōfuku-ji autumn canopies",
                "time": "14:00-15:30",
                "category": "Culture",
                "region": "Kyoto",
                "description": "Stroll across Tsutenkyo Bridge for jaw-dropping maple valley views "
                "and temple gardens.",
                "logistics": "Keihan to Tofukuji Station; timed entry queue moves quickly (~20 "
                "min).",
                "booking": "Purchase timed tickets online if available; otherwise buy on arrival "
                "(¥1,000).",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Tofuku-ji Temple",
                "budget_jpy": 4000,
                "notes": "Visit Kaisando for quieter contemplation.",
            },
            {
                "name": "Kōdai-ji night illumination",
                "time": "18:00-19:30",
                "category": "Culture",
                "region": "Kyoto",
                "description": "Nighttime light-up across Zen gardens and bamboo grove, culminating "
                "in mirror pond projections.",
                "logistics": "Taxi from Tofuku-ji (15 min). Evening entry ¥1,000; ends 21:30.",
                "booking": "Buy combo ticket with Entoku-in for extra installations.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Kodaiji Temple",
                "budget_jpy": 4000,
                "notes": "Return to Osaka via Keihan Gion-Shijo after illumination.",
            },
        ],
    },
    {
        "date": "2025-11-30",
        "weekday": "Sunday",
        "title": "Osaka soft landing & farewell",
        "lodging": "—",
        "summary": "Wrap with brunch, outlet spree, and calm airport send-off.",
        "nanako_work": False,
        "friends": "You + Nana",
        "entries": [
            {
                "name": "Takamura Wine & Coffee farewell brunch",
                "time": "10:00-11:30",
                "category": "Food",
                "region": "Osaka",
                "description": "Celebrate the journey with artisanal coffee cupping and light "
                "brunch in a lofted roastery.",
                "logistics": "Taxi from W Osaka (10 min). Reserve tasting flight with seasonal "
                "beans.",
                "booking": "Book cupping session for two; pick up beans for home brewing.",
                "companions": "You + Nana + Nicole + Ken",
                "google_query": "Takamura Wine & Coffee Roasters",
                "budget_jpy": 8000,
                "notes": "Share highlight reel before heading to airport.",
            },
            {
                "name": "Rinku Premium Outlets spree",
                "time": "13:00-16:00",
                "category": "Shopping",
                "region": "Izumisano",
                "description": "Outlet hop for last-minute gifts—Onitsuka Tiger, Coach, Nintendo "
                "Tokyo satellite—and sunset pier views.",
                "logistics": "JR rapid or Nankai to Rinku-Town (40 min). Use hands-free delivery "
                "counter for extra bags.",
                "booking": "Download coupon QR via official site for extra 10% savings.",
                "companions": "You + Nana",
                "google_query": "Rinku Premium Outlets",
                "budget_jpy": 30000,
                "notes": "Ride Rinku OOTD Ferris wheel if time allows.",
            },
            {
                "name": "Kansai International Airport departure",
                "time": "18:00-23:00",
                "category": "Departure",
                "region": "Osaka",
                "description": "Check in early, enjoy KIX Lounge showers, and savour final takoyaki "
                "before overnight flight home.",
                "logistics": "Hotel limo or Nankai Rapi:t to KIX (~45 min). Arrive 3 hours "
                "pre-flight for tax-free refund pickup.",
                "booking": "Confirm airline upgrade waitlist; pre-book KIX lounge seats via "
                "Priority Pass.",
                "companions": "You + Nana",
                "google_query": "Kansai International Airport",
                "budget_jpy": 0,
                "notes": "Allow lounge time and final takoyaki run.",
            },
        ],
    },
    {
        "date": "",
        "weekday": "Flex",
        "title": "Pick & mix adventures (optional buffer)",
        "lodging": "Flexible",
        "summary": "Hold for weather shifts, friend add-ons, or spontaneous cravings inspired by last "
        "year’s wish list.",
        "nanako_work": False,
        "friends": "Mix of Nana, Nicole, Ken, James, Phil,",
        "entries": [
            {
                "name": "Soosh Harajuku styling session",
                "time": "TBD",
                "category": "Shopping",
                "region": "Tokyo Harajuku",
                "description": "Drop into Soosh for curated streetwear and accessory edits.",
                "logistics": "Check Instagram for pop-up hours; typically inside Laforet.",
                "booking": "DM for personal styling slot if weekend.",
                "companions": "Fashion squad",
                "google_query": "Soosh Harajuku",
                "budget_jpy": 12000,
                "notes": "Good rainy-day filler before or after Harajuku plan.",
            },
            {
                "name": "Don Quijote Dotonbori skincare haul",
                "time": "TBD",
                "category": "Shopping",
                "region": "Osaka Minami",
                "description": "Stock up on J-beauty, sheet masks, and quirky gadgets late-night.",
                "logistics": "Open 24h; bring passport for tax-free counter.",
                "booking": "No booking; plan 23:00 visit to avoid crowds.",
                "companions": "You + Nana",
                "google_query": "Don Quijote Dotonbori",
                "budget_jpy": 15000,
                "notes": "Target Anessa SPF, LuLuLun masks, and limited matcha kit.",
            },
            {
                "name": "Maidreamin Akihabara kawaii break",
                "time": "TBD",
                "category": "Experience",
                "region": "Tokyo Akihabara",
                "description": "Enjoy pastel parfaits, silly chants, and polaroid keepsakes with "
                "maids.",
                "logistics": "Akihabara Central Exit; allow 60 minutes including show time.",
                "booking": "Reserve weekend slots via website to avoid queue.",
                "companions": "Nicole + Ken + Shin (optional)",
                "google_query": "Maidreamin Akihabara",
                "budget_jpy": 5000,
                "notes": "Great filler after electronics shopping.",
            },
            {
                "name": "Animate Ikebukuro flagship mission",
                "time": "TBD",
                "category": "Shopping",
                "region": "Tokyo Ikebukuro",
                "description": "Hunt anime figures, BL merch, and limited drops across eight "
                "floors.",
                "logistics": "Near Ikebukuro East Exit; use tax-free at level 8.",
                "booking": "No booking; plan weekday visit for minimal queue.",
                "companions": "Anime crew",
                "google_query": "Animate Ikebukuro Flagship Store",
                "budget_jpy": 10000,
                "notes": "Pick up Ghibli & Genshin collab goods.",
            },
            {
                "name": "GiGO Shibuya arcade showdown",
                "time": "TBD",
                "category": "Entertainment",
                "region": "Tokyo Shibuya",
                "description": "Compete in rhythm games, claw machines, and photobooths.",
                "logistics": "Located near Center-Gai; use cash or IC for machines.",
                "booking": "No booking; late-night energy boost.",
                "companions": "You + Nana + Friends",
                "google_query": "GiGO Shibuya",
                "budget_jpy": 4000,
                "notes": "Perfect rain alternative to outdoor plans.",
            },
            {
                "name": "Cinnamoroll Cafe sweet pause",
                "time": "TBD",
                "category": "Food",
                "region": "Tokyo Shinjuku",
                "description": "Pastel latte art and themed plates inside the Cinnamoroll "
                "dreamscape.",
                "logistics": "Located in Shinjuku; queue early for morning slots.",
                "booking": "Advance reservations via EPARK recommended.",
                "companions": "Nicole + Ken",
                "google_query": "Cinnamoroll Cafe Shinjuku",
                "budget_jpy": 3500,
                "notes": "Collect seasonal merch for birthday gift bags.",
            },
            {
                "name": "Genshin Impact Official Shop Tokyo",
                "time": "TBD",
                "category": "Shopping",
                "region": "Tokyo Shibuya",
                "description": "Snag exclusive character drops and photo spots for Shin’s fandom.",
                "logistics": "Inside PARCO; check reservation lottery during new releases.",
                "booking": "Use PARCO app to secure timed entry if new merch drop.",
                "companions": "Nicole (Shin) + Ken",
                "google_query": "Genshin Impact Official Store Shibuya PARCO",
                "budget_jpy": 9000,
                "notes": "Grab resin for cosplay upgrades and friend gifts.",
            },
            {
                "name": "Ichiran Shibuya late-night ramen",
                "time": "TBD",
                "category": "Food",
                "region": "Tokyo Shibuya",
                "description": "Post-party ramen fix with custom spice levels and solo booths.",
                "logistics": "Open 24h; use ticket machine and call button for refills.",
                "booking": "No booking; good filler after karaoke.",
                "companions": "You + Nicole + Ken",
                "google_query": "Ichiran Shibuya",
                "budget_jpy": 2000,
                "notes": "Try limited yuzu pepper toppings.",
            },
            {
                "name": "Matcha House Kyoto Kawaramachi desserts",
                "time": "TBD",
                "category": "Food",
                "region": "Kyoto Kawaramachi",
                "description": "Velvety matcha tiramisu and parfaits for sweet tooth afternoons.",
                "logistics": "Near Kawaramachi Station; queue ~20 minutes weekends.",
                "booking": "No booking; join waitlist via tablet at entrance.",
                "companions": "You + Nana",
                "google_query": "MACCHA HOUSE Kyoto Kawaramachi",
                "budget_jpy": 1800,
                "notes": "Ideal after Philosopher’s Path if weather turns.",
            },
            {
                "name": "Imperial Palace East Gardens stroll",
                "time": "TBD",
                "category": "Culture",
                "region": "Tokyo Chiyoda",
                "description": "Peaceful gardens with Edo Castle ruins—great midweek breather.",
                "logistics": "Enter via Otemon Gate; closed Mondays/Fridays.",
                "booking": "No booking; free entry with bag check.",
                "companions": "You + Nana",
                "google_query": "Imperial Palace East Gardens",
                "budget_jpy": 0,
                "notes": "Capture postcard for Nana’s grandparents.",
            },
            {
                "name": "NHK Studio Park souvenir hunt",
                "time": "TBD",
                "category": "Shopping",
                "region": "Tokyo Shibuya",
                "description": "Explore broadcasting exhibits and pick NHK gifts for Bayliss.",
                "logistics": "Shibuya Scramble Square building; check open days before visiting.",
                "booking": "Reserve free timed entry online when reopened.",
                "companions": "You + Nana",
                "google_query": "NHK Studio Park",
                "budget_jpy": 2000,
                "notes": "Buy Domo-kun plush for Bayliss to mark request.",
            },
        ],
    },
]
