from typing import Dict


PLACE_QUERIES: Dict[str, str] = {'& COFFEE MAISON KITSUNE Osaka': '& COFFEE MAISON KITSUNE Osaka',
 'Afuri Harajuku': 'Afuri Harajuku ramen',
 'Animate Ikebukuro Flagship Store': 'Animate Ikebukuro Flagship Store',
 'Arashiyama Bamboo Grove': 'Arashiyama Bamboo Grove',
 'Arashiyama Yoshimura': 'Arashiyama Yoshimura',
 'Arima Onsen Taiko-no-yu': 'Arima Onsen Taiko-no-yu',
 'Asakusa Imahan (Honten)': 'Asakusa Imahan (Honten)',
 'Bar Nayuta': 'Bar Nayuta',
 'Bear Paw Cafe Hirakata': 'Bear Paw Cafe Hirakata',
 'Brooklyn Roasting Company Kitahama': 'Brooklyn Roasting Company Kitahama',
 'Café & Meal MUJI Hirakata T-SITE': 'Café & Meal MUJI Hirakata T-SITE',
 'Cat Street Harajuku': 'Cat Street Tokyo',
 'Cinnamoroll Cafe Shinjuku': 'Cinnamoroll Cafe Shinjuku',
 'Daikanyama T-Site': 'Daikanyama T-Site',
 'Daimaru Shinsaibashi': 'Daimaru Shinsaibashi',
 'Disney Ambassador Hotel': 'Disney Ambassador Hotel',
 'Don Quijote Dotonbori': 'Don Quijote Dotonbori',
 'Donguri Republic Shinsaibashi': 'Donguri Republic Shinsaibashi',
 'Dotonbori': 'Dotonbori',
 'Eikan-do Zenrin-ji': 'Eikan-do Zenrin-ji',
 'Eko-in Temple': 'Eko-in Temple',
 'Eko-in Temple morning service': 'Eko-in Temple Koyasan',
 'Fushimi Inari Taisha': 'Fushimi Inari Taisha',
 'Gekkeikan Okura Sake Museum': 'Gekkeikan Okura Sake Museum',
 'Genshin Impact Official Store Shibuya PARCO': 'Genshin Impact Official Store Shibuya PARCO',
 'GiGO Shibuya': 'GiGO Shibuya arcade',
 'Gokurakuyu Hirakata': 'Gokurakuyu Hirakata',
 'Gonpachi Shibuya': 'Gonpachi Shibuya',
 'Grand Front Osaka Umekita Cellar': 'Grand Front Osaka Umekita Cellar',
 'HEP FIVE Ferris Wheel': 'HEP FIVE Ferris Wheel',
 'Himeji Castle': 'Himeji Castle',
 'Hirakata Park': 'Hirakata Park',
 'Hirakata T-SITE': 'Hirakata T-SITE',
 'Hotel Agora Osaka Moriguchi': 'Hotel Agora Osaka Moriguchi',
 'Hozenji Yokocho': 'Hozenji Yokocho',
 'Human Beings Everybody Noodles': 'Human Beings Everybody Noodles',
 'Ichiran Dotonbori': 'Ichiran Dotonbori',
 'Ichiran Shibuya': 'Ichiran Shibuya',
 'Imperial Palace East Gardens': 'Imperial Palace East Gardens',
 'Kaikaya by the Sea': 'Kaikaya by the Sea',
 'Kansai International Airport': 'Kansai International Airport',
 'Kansai International Airport Terminal 1': 'Kansai International Airport Terminal 1',
 'Karaoke Kan Shibuya': 'Karaoke Kan Shibuya',
 'Karaoke Kan Shinsaibashi 2-chome': 'Karaoke Kan Shinsaibashi 2-chome',
 'Kimono Forest': 'Kimono Forest',
 'Kobe Harborland': 'Kobe Harborland',
 'Kobe Nunobiki Herb Gardens': 'Kobe Nunobiki Herb Gardens',
 'Kodaiji Temple': 'Kodaiji Temple',
 'Kongobuji Temple': 'Kongobuji Temple',
 'Kuromon Ichiba Market': 'Kuromon Ichiba Market',
 'Kushikatsu Tanaka Hirakata': 'Kushikatsu Tanaka Hirakata',
 'Kuzuha Mall': 'Kuzuha Mall',
 'Kyoto Yakiniku Hiro Shijo Kiyamachi': 'Kyoto Yakiniku Hiro Shijo Kiyamachi',
 'LUCUA Food Hall': 'LUCUA Food Hall',
 'MACCHA HOUSE Kyoto Kawaramachi': 'MACCHA HOUSE Kyoto Kawaramachi',
 'MIMARU Tokyo Shinjuku WEST': 'MIMARU Tokyo Shinjuku WEST',
 'MIMARU Tokyo Shinjuku West': 'MIMARU Tokyo Shinjuku West',
 'MYDO Teppanyaki': 'MYDO Teppanyaki',
 'Maidreamin Akihabara': 'Maidreamin Akihabara',
 'Meiji Jingu Shrine': 'Meiji Jingu Shrine',
 'Mizuno': 'Mizuno Dotonbori',
 'NHK Studio Park': 'NHK Studio Park',
 'Nakameguro River Walk': 'Nakameguro River Walk',
 'Namba Yasaka Shrine': 'Namba Yasaka Shrine',
 'Nankai Koyasan Cable Car': 'Nankai Koyasan Cable Car',
 'Nozomi Shinkansen Shin-Osaka to Tokyo': 'Shin-Osaka Station Nozomi Shinkansen',
 'Nozomi Shinkansen Tokyo to Shin-Osaka': 'Tokyo Station Nozomi Shinkansen',
 'OMO7 Osaka by Hoshino Resorts': 'OMO7 Osaka by Hoshino Resorts',
 'Okunoin Cemetery': 'Okunoin Cemetery Koyasan',
 'Okutan Nanzenji': 'Okutan Nanzenji',
 'Osaka Aquarium Kaiyukan': 'Osaka Aquarium Kaiyukan',
 'Osaka Castle Museum': 'Osaka Castle Museum',
 'Osaka Museum of Housing and Living': 'Osaka Museum of Housing and Living',
 'Palette Town Ferris Wheel': 'Palette Town Ferris Wheel',
 'Philosopher’s Path': 'Philosopher’s Path',
 'Pokémon Café Nihonbashi': 'Pokémon Café Nihonbashi',
 'Rinku Premium Outlets': 'Rinku Premium Outlets',
 'SHIBUYA SKY': 'SHIBUYA SKY',
 'Senso-ji': 'Senso-ji Temple',
 'Shibuya 109': 'Shibuya 109',
 'Shibuya Crossing': 'Shibuya Crossing',
 'Shinsaibashi-suji Shopping Street': 'Shinsaibashi-suji Shopping Street',
 'Soosh Harajuku': 'Soosh Harajuku',
 'Steakland Kobe': 'Steakland Kobe',
 'Takamura Wine & Coffee Roasters': 'Takamura Wine & Coffee Roasters',
 'Takeshita Street': 'Takeshita Street',
 'Tempozan Marketplace': 'Tempozan Marketplace Osaka',
 'Tenryu-ji Temple': 'Tenryu-ji Temple',
 'Tofuku-ji Temple': 'Tofuku-ji Temple',
 'Tokyo Character Street': 'Tokyo Character Street',
 'Tokyo DisneySea': 'Tokyo DisneySea',
 'Tokyo Skytree': 'Tokyo Skytree',
 'Tombori River Cruise': 'Tombori River Cruise',
 'Torame Yokocho': 'Torame Yokocho',
 'Torisei Hirakata': 'Torisei Hirakata',
 'Toyosu Market Daiwa Sushi': 'Toyosu Market Daiwa Sushi',
 'Tsuen Tea': 'Tsuen Tea Uji',
 'Umeda Sky Building': 'Umeda Sky Building',
 'W Osaka': 'W Osaka',
 'sequence MIYASHITA PARK': 'sequence MIYASHITA PARK',
 'teamLab Botanical Garden Osaka': 'teamLab Botanical Garden Osaka',
 'teamLab Planets TOKYO': 'teamLab Planets TOKYO'}
