from typing import Any, Dict, List

from .itinerary_days import ITINERARY_DAYS
from .place_queries import PLACE_QUERIES

JPY_PER_GBP: float = 185.0
PACKING_ITEMS: List[Dict[str, Any]] = [
    {
        'name': 'Passports + Visit Japan Web QR',
        'category': 'Travel Essentials',
        'owner': 'Shared',
        'quantity': '2',
        'status': 'To Pack',
        'notes': 'Keep in RFID pouch with Visit Japan Web screenshots for KIX arrival (Day 1).',
        'linked_days': 'Day 1 & Day 17',
    },
    {
        'name': 'Flight e-tickets & insurance docs',
        'category': 'Travel Essentials',
        'owner': 'You',
        'quantity': 'Digital + 1 printed set',
        'status': 'To Print',
        'notes': 'Store PDFs in Notion + Apple Wallet; print extra copy for Disney/USJ verification.',
        'linked_days': 'All travel days',
    },
    {
        'name': 'Multi-currency wallet (¥ cash + IC cards)',
        'category': 'Money & Access',
        'owner': 'Shared',
        'quantity': '¥120,000 + 2 IC cards',
        'status': 'Prep',
        'notes': 'Preload ICOCA with ¥5,000 each; stash emergency £ notes.',
        'linked_days': 'Daily transit',
    },
    {
        'name': 'Shinkansen & limited express reservations',
        'category': 'Travel Essentials',
        'owner': 'You',
        'quantity': 'smartEX reservations + QR',
        'status': 'Book',
        'notes': 'Reserve Nozomi (Nov 21 & 25) + guest seats for Nicole & Ken (Nov 28).',
        'linked_days': 'Days 8, 12, 15',
    },
    {
        'name': 'JR/Keihan rail pass kit',
        'category': 'Travel Essentials',
        'owner': 'Shared',
        'quantity': '1 Kansai-Thru Pass + 1 Keihan card sleeve',
        'status': 'To Buy',
        'notes': 'Purchase Kansai Thru Pass at KIX; load Hirakata/Osaka itinerary inside.',
        'linked_days': 'Days 1-8, 12-17',
    },
    {
        'name': 'Layering wardrobe (Heattech sets)',
        'category': 'Clothing',
        'owner': 'Shared',
        'quantity': '4 base sets each',
        'status': 'Pack',
        'notes': 'Mix neutrals for Osaka city looks + Kyoto temple modesty.',
        'linked_days': 'All outdoor days',
    },
    {
        'name': 'Outerwear duo (wool coat + packable down)',
        'category': 'Clothing',
        'owner': 'You',
        'quantity': '2 jackets',
        'status': 'Pack',
        'notes': 'Down jacket compresses for Tokyo Disney nights; wool coat for birthday dinner.',
        'linked_days': 'Days 9-16',
    },
    {
        'name': 'Footwear rotation',
        'category': 'Clothing',
        'owner': 'Shared',
        'quantity': 'Waterproof sneakers + dress boots + indoor slippers',
        'status': 'Pack',
        'notes': 'Break-in sneakers beforehand; pack foldable slippers for ryokan + Airbnb.',
        'linked_days': 'Koyasan stay, Tokyo apartment, W Osaka',
    },
    {
        'name': 'Onsen & sentō kit',
        'category': 'Wellness',
        'owner': 'Shared',
        'quantity': 'Mesh bag with towels, toiletries, tattoo covers',
        'status': 'Pack',
        'notes': 'Include modest swimwear for spa zones + waterproof phone pouch.',
        'linked_days': 'Days 5, 6, 13',
    },
    {
        'name': 'Koyasan overnight tote',
        'category': 'Logistics',
        'owner': 'Shared',
        'quantity': 'Carry-on with thermals, toiletries, chargers',
        'status': 'Prep',
        'notes': 'Keep essentials for the temple stay while main luggage forwards to Osaka.',
        'linked_days': 'Day 6',
    },
    {
        'name': 'Sleepwear & loungewear',
        'category': 'Clothing',
        'owner': 'Shared',
        'quantity': 'Lightweight set + cosy set each',
        'status': 'Pack',
        'notes': 'Mix-match for ryokan tatami nights and Tokyo sleepover aesthetic.',
        'linked_days': 'Days 6, 9-10, 15',
    },
    {
        'name': 'Birthday outfits & accessories',
        'category': 'Style',
        'owner': 'Shared',
        'quantity': 'Neon glam look + backup smart casual',
        'status': 'Prep',
        'notes': 'Coordinate colour palette with Nicole & Ken; pack LED hair clips.',
        'linked_days': 'Day 15',
    },
    {
        'name': 'Camera & content kit',
        'category': 'Tech',
        'owner': 'You',
        'quantity': 'Mirrorless body, 24mm + 50mm primes, DJI Pocket, mini tripod',
        'status': 'Charge',
        'notes': 'Pack extra SD cards + ND filter for teamLab and Shibuya Sky.',
        'linked_days': 'Days 2-16',
    },
    {
        'name': 'Power & charging hub',
        'category': 'Tech',
        'owner': 'Shared',
        'quantity': '2 multi-USB bricks, 4 Type-A cables, 2 USB-C cables, 1 power board',
        'status': 'Pack',
        'notes': 'Add spare adapter for Nicole & Ken during Osaka stay.',
        'linked_days': 'All days',
    },
    {
        'name': 'Connectivity pack',
        'category': 'Tech',
        'owner': 'You',
        'quantity': 'eSIM QR + pocket Wi-Fi + SIM ejector',
        'status': 'Activate',
        'notes': 'Activate Ubigi eSIM 24h before departure; charge pocket Wi-Fi nightly.',
        'linked_days': 'Days 1-17',
    },
    {
        'name': 'Nintendo Switch party set',
        'category': 'Entertainment',
        'owner': 'You',
        'quantity': 'Switch OLED + Joy-Cons + Just Dance + Mario Kart',
        'status': 'Pack',
        'notes': 'Preload party playlist + update software before Nov 22 sleepover.',
        'linked_days': 'Day 10',
    },
    {
        'name': 'Wellness & med pouch',
        'category': 'Health',
        'owner': 'Shared',
        'quantity': 'Travel meds, motion sickness bands, pain relief patches',
        'status': 'Restock',
        'notes': 'Include allergy meds for autumn pollen; keep duplicates in day bag.',
        'linked_days': 'All',
    },
    {
        'name': 'Skincare + sheet mask caddy',
        'category': 'Health',
        'owner': 'Nana',
        'quantity': 'Routine minis + hydrating masks',
        'status': 'Pack',
        'notes': 'Share brightening masks with Nicole & Ken during Tokyo sleepover.',
        'linked_days': 'Days 9-15',
    },
    {
        'name': 'Hair & styling toolkit',
        'category': 'Style',
        'owner': 'Shared',
        'quantity': 'Dual-voltage straightener, curl wand, styling clips',
        'status': 'Pack',
        'notes': 'Essential for birthday glam + Harajuku looks.',
        'linked_days': 'Days 9 & 15',
    },
    {
        'name': 'Aussie gift stash',
        'category': 'Gifts',
        'owner': 'You',
        'quantity': 'Tim Tams, Indigenous art tea towels, mini boomerangs',
        'status': 'Pack',
        'notes': 'Wrap individually for friends + Nana’s coworkers; include handwritten notes.',
        'linked_days': 'Days 9, 15',
    },
    {
        'name': 'Tea & sake carrier tube',
        'category': 'Shopping Support',
        'owner': 'Shared',
        'quantity': 'Protective tube for bottles & tea canisters',
        'status': 'Pack',
        'notes': 'Use for Uji purchases + Gekkeikan tasting souvenirs.',
        'linked_days': 'Days 4, 5, 16',
    },
    {
        'name': 'Birthday décor & confetti kit',
        'category': 'Celebration',
        'owner': 'You',
        'quantity': 'LED candles, tassel garland, sparkler candles',
        'status': 'Pack',
        'notes': 'Pack in hard case; set up at W Osaka before dinner.',
        'linked_days': 'Day 15',
    },
    {
        'name': 'Travel journal & Instax mini',
        'category': 'Memories',
        'owner': 'Shared',
        'quantity': 'Dot-grid notebook + Instax camera + 40 films',
        'status': 'Pack',
        'notes': 'Collect stamps and Polaroids for Notion scrapbook import.',
        'linked_days': 'Daily reflection',
    },
    {
        'name': 'Reusable shopping bags & compression cubes',
        'category': 'Logistics',
        'owner': 'Shared',
        'quantity': '3 foldable totes + 4 packing cubes + vacuum bag',
        'status': 'Pack',
        'notes': 'Needed for Tokyo shopping haul + Kyoto leaf souvenirs.',
        'linked_days': 'Days 8-17',
    },
    {
        'name': 'Laundry + steamer pouch',
        'category': 'Logistics',
        'owner': 'Shared',
        'quantity': 'Travel steamer, detergent sheets, collapsible hamper',
        'status': 'Pack',
        'notes': 'Use at the temple stay and Tokyo apartment for mid-trip refresh.',
        'linked_days': 'Days 6, 10, 12',
    },
    {
        'name': 'Emergency snack pack',
        'category': 'Food',
        'owner': 'You',
        'quantity': 'Protein bars, Berocca, electrolytes',
        'status': 'Pack',
        'notes': 'Great for long park days (USJ, Disney) and early train mornings.',
        'linked_days': 'Days 9, 11, 14',
    },
]
EXPENSE_ITEMS: List[Dict[str, Any]] = [
    {
        'name': 'Return flights (AUS → KIX)',
        'category': 'Transport',
        'date': '2025-11-14',
        'city': 'International',
        'type': 'Flight',
        'estimated_cost_jpy': 240000,
        'payment_method': 'Credit Card (Qantas FF)',
        'status': 'Booked',
        'notes': 'Redeemed partial points; cash component to be settled in Oct 2025.',
        'linked_days': 'Days 1 & 17',
    },
    {
        'name': 'Hotel Agora Osaka Moriguchi (8 nights)',
        'category': 'Lodging',
        'date': '2025-11-14',
        'city': 'Osaka',
        'type': 'Hotel',
        'estimated_cost_jpy': 192000,
        'payment_method': 'Credit Card',
        'status': 'Reserve in Aug',
        'notes': 'Bundle breakfast on work days; flexible cancellation until Nov 1.',
        'linked_days': 'Days 1-5, 8, 12-14',
    },
    {
        'name': 'Eko-in Temple shukubo stay',
        'category': 'Lodging',
        'date': '2025-11-19',
        'city': 'Koyasan',
        'type': 'Temple Stay',
        'estimated_cost_jpy': 42000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': 'Includes shojin dinner, breakfast, meditation, and lantern night tour.',
        'linked_days': 'Day 6',
    },
    {
        'name': 'OMO7 Osaka by Hoshino Resorts',
        'category': 'Lodging',
        'date': '2025-11-20',
        'city': 'Osaka',
        'type': 'Hotel',
        'estimated_cost_jpy': 32000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': 'Add onsen access + late checkout request.',
        'linked_days': 'Day 7',
    },
    {
        'name': 'sequence MIYASHITA PARK',
        'category': 'Lodging',
        'date': '2025-11-21',
        'city': 'Tokyo',
        'type': 'Hotel',
        'estimated_cost_jpy': 52000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': 'Two single nights (Nov 21 & 24) to keep Shibuya base; request park-view room; deposit refundable until Nov 15.',
        'linked_days': 'Days 8 & 11',
    },
    {
        'name': 'MIMARU Tokyo Shinjuku WEST',
        'category': 'Lodging',
        'date': '2025-11-22',
        'city': 'Tokyo',
        'type': 'Apartment Hotel',
        'estimated_cost_jpy': 36000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': 'Sleepover suite for 4 with breakfast hamper; add projector rental for Mario Kart tournament.',
        'linked_days': 'Days 9-10',
    },
    {
        'name': 'W Osaka (Marvelous Suite, 2 nights)',
        'category': 'Lodging',
        'date': '2025-11-28',
        'city': 'Osaka',
        'type': 'Hotel',
        'estimated_cost_jpy': 190000,
        'payment_method': 'Bonvoy Points + Cash',
        'status': 'To Book',
        'notes': 'Use Suite Night Awards; request late checkout Nov 30.',
        'linked_days': 'Days 15-17',
    },
    {
        'name': 'Haruka Express + ICOCA bundle (2 pax)',
        'category': 'Transport',
        'date': '2025-11-14',
        'city': 'Osaka',
        'type': 'Rail',
        'estimated_cost_jpy': 10400,
        'payment_method': 'Cash',
        'status': 'To Buy',
        'notes': 'Purchase at KIX JR desk on arrival.',
        'linked_days': 'Day 1',
    },
    {
        'name': 'Kansai Thru Pass (3-day) + Keihan upgrades',
        'category': 'Transport',
        'date': '2025-11-15',
        'city': 'Osaka/Kyoto',
        'type': 'Rail',
        'estimated_cost_jpy': 10000,
        'payment_method': 'Cash',
        'status': 'To Buy',
        'notes': 'Covers Kyoto/Nara/Kobe days; add limited express seats as needed.',
        'linked_days': 'Days 3-4, 6, 13, 16',
    },
    {
        'name': 'Nozomi Shinkansen (Osaka↔Tokyo round trip + guest leg)',
        'category': 'Transport',
        'date': '2025-11-21',
        'city': 'Tokyo',
        'type': 'Rail',
        'estimated_cost_jpy': 84000,
        'payment_method': 'smartEX',
        'status': 'To Book',
        'notes': 'Outbound Nov 21, return Nov 25 for you + Nana; add Nov 28 Tokyo→Osaka guest leg for Nicole & Ken.',
        'linked_days': 'Days 8, 12, 15',
    },
    {
        'name': 'Urban transport top-ups (Tokyo/Osaka)',
        'category': 'Transport',
        'date': '2025-11-22',
        'city': 'Tokyo/Osaka',
        'type': 'Transit',
        'estimated_cost_jpy': 12000,
        'payment_method': 'IC Card',
        'status': 'Budget',
        'notes': 'Daily subway spend across Shibuya, Harajuku, Osaka loops.',
        'linked_days': 'All city days',
    },
    {
        'name': 'Taxi & rideshare buffer',
        'category': 'Transport',
        'date': '2025-11-19',
        'city': 'Kyoto/Osaka/Tokyo',
        'type': 'Transport',
        'estimated_cost_jpy': 15000,
        'payment_method': 'Cash',
        'status': 'Budget',
        'notes': 'Kyoto tea ceremony transfers, late-night Osaka rides.',
        'linked_days': 'Days 6, 7, 15',
    },
    {
        'name': 'teamLab Botanical Garden Osaka tickets',
        'category': 'Experiences',
        'date': '2025-11-15',
        'city': 'Osaka',
        'type': 'Art Installation',
        'estimated_cost_jpy': 3600,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': '18:00 slot for two.',
        'linked_days': 'Day 2',
    },
    {
        'name': 'Camellia Garden private tea ceremony',
        'category': 'Experiences',
        'date': '2025-11-19',
        'city': 'Kyoto',
        'type': 'Workshop',
        'estimated_cost_jpy': 12000,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': 'Private session for two with English host.',
        'linked_days': 'Day 6',
    },
    {
        'name': 'Okunoin lantern night tour',
        'category': 'Experiences',
        'date': '2025-11-19',
        'city': 'Koyasan',
        'type': 'Guided Tour',
        'estimated_cost_jpy': 6000,
        'payment_method': 'Cash',
        'status': 'To Book',
        'notes': 'Reserve English lantern walk via Eko-in concierge; includes protective talisman.',
        'linked_days': 'Day 6',
    },
    {
        'name': 'Tsuen Tea master tasting',
        'category': 'Experiences',
        'date': '2025-11-17',
        'city': 'Uji',
        'type': 'Workshop',
        'estimated_cost_jpy': 5000,
        'payment_method': 'Cash',
        'status': 'To Book',
        'notes': 'Reserve counter seats; includes souvenirs.',
        'linked_days': 'Day 4',
    },
    {
        'name': 'Gekkeikan Sake tasting flight',
        'category': 'Experiences',
        'date': '2025-11-16',
        'city': 'Kyoto',
        'type': 'Tasting',
        'estimated_cost_jpy': 2000,
        'payment_method': 'Cash',
        'status': 'To Pay',
        'notes': 'Add museum entry + bottle shipping.',
        'linked_days': 'Day 3',
    },
    {
        'name': 'Tonbori River Cruise',
        'category': 'Experiences',
        'date': '2025-11-14',
        'city': 'Osaka',
        'type': 'Tour',
        'estimated_cost_jpy': 2400,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': 'Reserve sunset sailing with QR voucher.',
        'linked_days': 'Day 1',
    },
    {
        'name': 'Umeda Sky Building Observatory',
        'category': 'Experiences',
        'date': '2025-11-20',
        'city': 'Osaka',
        'type': 'Viewpoint',
        'estimated_cost_jpy': 6000,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': 'Includes cocktails at Sky 40 bar.',
        'linked_days': 'Day 7',
    },
    {
        'name': 'Osaka Aquarium Kaiyukan twilight tickets',
        'category': 'Experiences',
        'date': '2025-11-20',
        'city': 'Osaka',
        'type': 'Attraction',
        'estimated_cost_jpy': 5400,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': '16:00 timed entry for two; add digital photo pass for manta ray shots.',
        'linked_days': 'Day 7',
    },
    {
        'name': 'Hirakata Park twilight tickets',
        'category': 'Experiences',
        'date': '2025-11-21',
        'city': 'Hirakata',
        'type': 'Theme Park',
        'estimated_cost_jpy': 3000,
        'payment_method': 'Cash',
        'status': 'Budget',
        'notes': 'Purchase at gate with twilight discount.',
        'linked_days': 'Day 8',
    },
    {
        'name': 'teamLab Planets TOKYO tickets',
        'category': 'Experiences',
        'date': '2025-11-23',
        'city': 'Tokyo',
        'type': 'Art Installation',
        'estimated_cost_jpy': 15200,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': '09:00 slot for four.',
        'linked_days': 'Day 10',
    },
    {
        'name': 'Pokémon Café prepayment',
        'category': 'Experiences',
        'date': '2025-11-23',
        'city': 'Tokyo',
        'type': 'Character Dining',
        'estimated_cost_jpy': 12000,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': 'Reservation deposit for four + souvenir mugs.',
        'linked_days': 'Day 10',
    },
    {
        'name': 'Shibuya Sky tickets',
        'category': 'Experiences',
        'date': '2025-11-24',
        'city': 'Tokyo',
        'type': 'Viewpoint',
        'estimated_cost_jpy': 13200,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': '18:00 sunset slot for 6 (James + Phil included); add souvenir photo pack.',
        'linked_days': 'Day 11',
    },
    {
        'name': 'Tokyo DisneySea + Premier Access',
        'category': 'Experiences',
        'date': '2025-11-22',
        'city': 'Tokyo',
        'type': 'Theme Park',
        'estimated_cost_jpy': 87200,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': 'Four passports plus Premier Access for Soaring, Journey, and Toy Story Mania.',
        'linked_days': 'Day 9',
    },
    {
        'name': 'Disney Ambassador Hyperion Lounge tea',
        'category': 'Food & Drink',
        'date': '2025-11-22',
        'city': 'Tokyo',
        'type': 'Tea Service',
        'estimated_cost_jpy': 20000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': 'Afternoon tea for four with seasonal set and birthday plating.',
        'linked_days': 'Day 9',
    },
    {
        'name': 'Universal Studios Japan tickets + Express 7',
        'category': 'Experiences',
        'date': '2025-11-27',
        'city': 'Osaka',
        'type': 'Theme Park',
        'estimated_cost_jpy': 104000,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': 'Pair with Super Nintendo timed entry + Kinopio’s Café lunch.',
        'linked_days': 'Day 14',
    },
    {
        'name': 'Arima Onsen Taiko-no-yu passes',
        'category': 'Experiences',
        'date': '2025-11-26',
        'city': 'Kobe',
        'type': 'Wellness',
        'estimated_cost_jpy': 8000,
        'payment_method': 'Cash',
        'status': 'To Pay',
        'notes': 'Includes private tatami lounge upgrade.',
        'linked_days': 'Day 13',
    },
    {
        'name': 'Kobe Nunobiki Herb Gardens ropeway combo',
        'category': 'Experiences',
        'date': '2025-11-27',
        'city': 'Kobe',
        'type': 'Attraction',
        'estimated_cost_jpy': 3600,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': 'Round-trip ropeway and garden entry for two; pre-book 09:30 departure.',
        'linked_days': 'Day 13',
    },
    {
        'name': 'Karaoke Kan Shibuya session',
        'category': 'Nightlife',
        'date': '2025-11-23',
        'city': 'Tokyo',
        'type': 'Entertainment',
        'estimated_cost_jpy': 18000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': '3-hour all-you-can-drink plan for four.',
        'linked_days': 'Day 10',
    },
    {
        'name': 'Karaoke Kan Shinsaibashi VIP',
        'category': 'Nightlife',
        'date': '2025-11-28',
        'city': 'Osaka',
        'type': 'Entertainment',
        'estimated_cost_jpy': 24000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': '3-hour premium room with open bar + props.',
        'linked_days': 'Day 15',
    },
    {
        'name': 'MYDO Teppanyaki birthday dinner',
        'category': 'Food & Drink',
        'date': '2025-11-28',
        'city': 'Osaka',
        'type': 'Fine Dining',
        'estimated_cost_jpy': 60000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': 'Set menu for four + dessert sparkler.',
        'linked_days': 'Day 15',
    },
    {
        'name': 'Bar Nayuta celebration cocktails',
        'category': 'Nightlife',
        'date': '2025-11-28',
        'city': 'Osaka',
        'type': 'Cocktail Bar',
        'estimated_cost_jpy': 16000,
        'payment_method': 'Credit Card',
        'status': 'Budget',
        'notes': 'Custom drink “Japlan Nova” + round of yuzu fizzes.',
        'linked_days': 'Day 15',
    },
    {
        'name': 'Eikan-dō & Kōdai-ji illumination tickets',
        'category': 'Experiences',
        'date': '2025-11-29',
        'city': 'Kyoto',
        'type': 'Night Illumination',
        'estimated_cost_jpy': 8000,
        'payment_method': 'Online',
        'status': 'To Book',
        'notes': 'Includes combo ticket for Entoku-in.',
        'linked_days': 'Day 16',
    },
    {
        'name': 'Foodie highlights fund (markets & street eats)',
        'category': 'Food & Drink',
        'date': '2025-11-15',
        'city': 'Osaka/Kyoto/Tokyo',
        'type': 'Daily Meals',
        'estimated_cost_jpy': 60000,
        'payment_method': 'Cash/IC',
        'status': 'Budget',
        'notes': 'Kuromon, Nishiki, Tsukiji outer market, Harajuku snacks.',
        'linked_days': 'Days 2-16',
    },
    {
        'name': 'Gifts & birthday décor budget',
        'category': 'Shopping',
        'date': '2025-11-10',
        'city': 'Pre-trip',
        'type': 'Supplies',
        'estimated_cost_jpy': 45000,
        'payment_method': 'Credit Card',
        'status': 'In Progress',
        'notes': 'Aussie gifts, confetti kit, custom cake topper, Polaroid film.',
        'linked_days': 'Days 9, 15',
    },
    {
        'name': 'Travel insurance (Comprehensive duo)',
        'category': 'Admin',
        'date': '2025-10-15',
        'city': 'Pre-trip',
        'type': 'Insurance',
        'estimated_cost_jpy': 28000,
        'payment_method': 'Credit Card',
        'status': 'Booked',
        'notes': 'Covers winter sports/onsen, electronics, cancellations.',
        'linked_days': 'Trip coverage',
    },
    {
        'name': 'Connectivity (eSIM + pocket Wi-Fi rental)',
        'category': 'Tech',
        'date': '2025-11-12',
        'city': 'Pre-trip',
        'type': 'Data',
        'estimated_cost_jpy': 8000,
        'payment_method': 'Credit Card',
        'status': 'To Book',
        'notes': 'Ubigi 30-day eSIM + Ninja Wi-Fi rental for backup.',
        'linked_days': 'All days',
    },
]
